const ALIBI_PUZZLES = [
  { category: "Types of cheese", words: ["Brie","Gouda","Cheddar","Feta","Stilton","Camembert","Manchego","Havarti"], culprit: "Quinoa", culpritHint: "Not a cheese — it's a grain" },
  { category: "Planets in our solar system", words: ["Mercury","Venus","Mars","Jupiter","Saturn","Uranus","Neptune","Earth"], culprit: "Pluto", culpritHint: "Reclassified as a dwarf planet in 2006" },
  { category: "Shakespeare plays", words: ["Hamlet","Othello","Macbeth","Tempest","Twelfth Night","Julius Caesar","King Lear","Coriolanus"], culprit: "Faustus", culpritHint: "Written by Christopher Marlowe, not Shakespeare" },
  { category: "Elements on the periodic table", words: ["Oxygen","Iron","Gold","Silver","Carbon","Helium","Neon","Zinc"], culprit: "Bronze", culpritHint: "An alloy (copper + tin), not an element" },
  { category: "Countries in Africa", words: ["Kenya","Nigeria","Ghana","Morocco","Egypt","Tanzania","Ethiopia","Senegal"], culprit: "Jamaica", culpritHint: "Jamaica is in the Caribbean, not Africa" },
  { category: "Bones in the human body", words: ["Femur","Tibia","Humerus","Radius","Ulna","Patella","Fibula","Sternum"], culprit: "Deltoid", culpritHint: "The deltoid is a muscle, not a bone" },
  { category: "Olympic sports", words: ["Fencing","Archery","Judo","Rowing","Boxing","Diving","Sailing","Handball"], culprit: "Cricket", culpritHint: "Cricket is not an Olympic sport" },
  { category: "Musical instruments with strings", words: ["Violin","Cello","Guitar","Harp","Banjo","Mandolin","Ukulele","Sitar"], culprit: "Oboe", culpritHint: "The oboe is a woodwind, not a string instrument" },
  { category: "Capital cities", words: ["Tokyo","Berlin","Ottawa","Canberra","Lima","Oslo","Cairo","Nairobi"], culprit: "Sydney", culpritHint: "Sydney is not Australia's capital — Canberra is" },
  { category: "Words that rhyme with 'night'", words: ["Light","Fight","Sight","Right","Might","Bright","Flight","Tight"], culprit: "Height", culpritHint: "Height ends in the same letters but doesn't rhyme" },
  { category: "Types of pasta", words: ["Penne","Fusilli","Rigatoni","Farfalle","Linguine","Orzo","Ravioli","Gnocchi"], culprit: "Risotto", culpritHint: "Risotto is a rice dish, not a pasta" },
  { category: "Freshwater fish", words: ["Trout","Bass","Catfish","Pike","Perch","Carp","Walleye","Bluegill"], culprit: "Tuna", culpritHint: "Tuna is a saltwater fish" },
  { category: "U.S. Presidents", words: ["Lincoln","Jefferson","Madison","Monroe","Jackson","Adams","Grant","Polk"], culprit: "Hamilton", culpritHint: "Hamilton was Treasury Secretary, never president" },
  { category: "Types of cloud", words: ["Cumulus","Stratus","Cirrus","Nimbus","Alto","Cumulonimbus","Stratocumulus","Cirrostratus"], culprit: "Nebula", culpritHint: "A nebula is in space, not in Earth's atmosphere" },
  { category: "Fruits that grow on trees", words: ["Apple","Mango","Cherry","Peach","Pear","Plum","Fig","Lemon"], culprit: "Strawberry", culpritHint: "Strawberries grow on low plants, not trees" },
  { category: "Dog breeds", words: ["Beagle","Poodle","Boxer","Collie","Husky","Dalmatian","Rottweiler","Bulldog"], culprit: "Calico", culpritHint: "Calico is a cat coat pattern, not a dog breed" },
  { category: "Greek gods", words: ["Zeus","Hera","Apollo","Athena","Hermes","Ares","Artemis","Poseidon"], culprit: "Jupiter", culpritHint: "Jupiter is the Roman name, not Greek" },
  { category: "Landlocked countries", words: ["Austria","Bolivia","Nepal","Mongolia","Zambia","Paraguay","Laos","Hungary"], culprit: "Portugal", culpritHint: "Portugal has an Atlantic coastline" },
  { category: "Words containing 'cat'", words: ["Catalog","Educate","Scatter","Locate","Vacation","Category","Indicate","Delicate"], culprit: "Castle", culpritHint: "'Castle' contains 'cas' not 'cat'" },
  { category: "Gemstones", words: ["Ruby","Emerald","Sapphire","Topaz","Opal","Garnet","Jade","Amethyst"], culprit: "Granite", culpritHint: "Granite is a common rock, not a gemstone" },
  { category: "South American countries", words: ["Brazil","Chile","Peru","Colombia","Argentina","Ecuador","Uruguay","Venezuela"], culprit: "Portugal", culpritHint: "Portugal is in Europe" },
  { category: "Types of dance", words: ["Waltz","Tango","Salsa","Ballet","Polka","Samba","Mambo","Foxtrot"], culprit: "Sonata", culpritHint: "A sonata is a musical composition, not a dance" },
  { category: "Bodies of water", words: ["Atlantic","Pacific","Caspian","Caribbean","Baltic","Adriatic","Arctic","Indian"], culprit: "Sahara", culpritHint: "The Sahara is a desert, not a body of water" },
  { category: "Prime numbers", words: ["Two","Three","Five","Seven","Eleven","Thirteen","Seventeen","Nineteen"], culprit: "Nine", culpritHint: "Nine is divisible by 3 — not prime" },
  { category: "Woodwind instruments", words: ["Flute","Clarinet","Oboe","Bassoon","Piccolo","Recorder","Saxophone","Fife"], culprit: "Trumpet", culpritHint: "Trumpet is brass, not woodwind" },
  { category: "Spices", words: ["Cumin","Paprika","Turmeric","Cinnamon","Nutmeg","Saffron","Cardamom","Coriander"], culprit: "Parsley", culpritHint: "Parsley is an herb, not a spice" },
  { category: "Islands", words: ["Sicily","Borneo","Java","Crete","Fiji","Malta","Corsica","Bali"], culprit: "Venice", culpritHint: "Venice is built on a lagoon but isn't an island" },
  { category: "Constellations", words: ["Orion","Cassiopeia","Scorpius","Perseus","Aquarius","Gemini","Draco","Lyra"], culprit: "Pluto", culpritHint: "Pluto is a dwarf planet, not a constellation" },
  { category: "Vegetables that grow underground", words: ["Potato","Carrot","Beet","Radish","Turnip","Parsnip","Ginger","Onion"], culprit: "Celery", culpritHint: "Celery grows above ground" },
  { category: "Nobel Prize categories", words: ["Physics","Chemistry","Medicine","Literature","Peace","Economics"], culprit: "Mathematics", culpritHint: "There is no Nobel Prize for Mathematics" },
  { category: "European rivers", words: ["Danube","Rhine","Thames","Seine","Volga","Elbe","Loire","Tiber"], culprit: "Amazon", culpritHint: "The Amazon flows through South America" },
  { category: "Mammals that can fly", words: ["Fruit Bat","Vampire Bat","Flying Fox","Horseshoe Bat","Brown Bat","Pipistrelle","Long-eared Bat","Megabat"], culprit: "Flying Squirrel", culpritHint: "Flying squirrels glide — they don't truly fly" },
  { category: "Silent letters in English", words: ["Knife","Gnome","Psalm","Wrist","Honest","Island","Doubt","Column"], culprit: "Pencil", culpritHint: "Every letter in 'pencil' is pronounced" },
  { category: "Types of bridge", words: ["Arch","Beam","Truss","Suspension","Cantilever","Cable-stayed","Drawbridge","Pontoon"], culprit: "Aqueduct", culpritHint: "An aqueduct carries water, it's not a bridge type" },
  { category: "Currencies", words: ["Dollar","Euro","Pound","Yen","Rupee","Franc","Krona","Won"], culprit: "Bitcoin", culpritHint: "Bitcoin is a cryptocurrency, not a national currency" }
];
