const QUOTES = [
  { text: "The only thing we have to fear is fear itself.", author: "Franklin D. Roosevelt" },
  { text: "To be or not to be, that is the question.", author: "William Shakespeare" },
  { text: "I think, therefore I am.", author: "Rene Descartes" },
  { text: "The unexamined life is not worth living.", author: "Socrates" },
  { text: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
  { text: "Knowledge is power.", author: "Francis Bacon" },
  { text: "Life is what happens when you are busy making other plans.", author: "John Lennon" },
  { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "The greatest glory in living lies not in never falling but in rising every time we fall.", author: "Nelson Mandela" },
  { text: "It is never too late to be what you might have been.", author: "George Eliot" },
  { text: "Be yourself. Everyone else is already taken.", author: "Oscar Wilde" },
  { text: "Two things are infinite: the universe and human stupidity.", author: "Albert Einstein" },
  { text: "Not all those who wander are lost.", author: "J.R.R. Tolkien" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
  { text: "Imagination is more important than knowledge.", author: "Albert Einstein" },
  { text: "Injustice anywhere is a threat to justice everywhere.", author: "Martin Luther King Jr." },
  { text: "Stay hungry, stay foolish.", author: "Steve Jobs" },
  { text: "The best way to predict the future is to invent it.", author: "Alan Kay" },
  { text: "A room without books is like a body without a soul.", author: "Marcus Tullius Cicero" },
  { text: "If you tell the truth you do not need a good memory.", author: "Mark Twain" },
  { text: "Float like a butterfly, sting like a bee.", author: "Muhammad Ali" },
  { text: "We are what we repeatedly do. Excellence is not an act but a habit.", author: "Aristotle" },
  { text: "The pen is mightier than the sword.", author: "Edward Bulwer-Lytton" },
  { text: "Darkness cannot drive out darkness, only light can do that.", author: "Martin Luther King Jr." },
  { text: "Where there is love there is life.", author: "Mahatma Gandhi" },
  { text: "An eye for an eye only ends up making the whole world blind.", author: "Mahatma Gandhi" },
  { text: "You miss one hundred percent of the shots you never take.", author: "Wayne Gretzky" },
  { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
  { text: "Do or do not, there is no try.", author: "Yoda" },
  { text: "What we know is a drop, what we do not know is an ocean.", author: "Isaac Newton" }
];
