const QUOTES = [
  { text: "The only thing we have to fear is fear itself.", author: "Franklin D. Roosevelt" },
  { text: "To be or not to be, that is the question.", author: "William Shakespeare" },
  { text: "I think, therefore I am.", author: "Rene Descartes" },
  { text: "The unexamined life is not worth living.", author: "Socrates" },
  { text: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
  { text: "Knowledge is power.", author: "Francis Bacon" },
  { text: "Life is what happens when you are busy making other plans.", author: "John Lennon" },
  { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "The greatest glory in living lies not in never falling but in rising every time we fall.", author: "Nelson Mandela" },
  { text: "It is never too late to be what you might have been.", author: "George Eliot" },
  { text: "Be yourself. Everyone else is already taken.", author: "Oscar Wilde" },
  { text: "Two things are infinite: the universe and human stupidity.", author: "Albert Einstein" },
  { text: "Not all those who wander are lost.", author: "J.R.R. Tolkien" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
  { text: "Imagination is more important than knowledge.", author: "Albert Einstein" },
  { text: "Injustice anywhere is a threat to justice everywhere.", author: "Martin Luther King Jr." },
  { text: "Stay hungry, stay foolish.", author: "Steve Jobs" },
  { text: "The best way to predict the future is to invent it.", author: "Alan Kay" },
  { text: "A room without books is like a body without a soul.", author: "Marcus Tullius Cicero" },
  { text: "If you tell the truth you do not need a good memory.", author: "Mark Twain" },
  { text: "Float like a butterfly, sting like a bee.", author: "Muhammad Ali" },
  { text: "We are what we repeatedly do. Excellence is not an act but a habit.", author: "Aristotle" },
  { text: "The pen is mightier than the sword.", author: "Edward Bulwer-Lytton" },
  { text: "Darkness cannot drive out darkness, only light can do that.", author: "Martin Luther King Jr." },
  { text: "Where there is love there is life.", author: "Mahatma Gandhi" },
  { text: "An eye for an eye only ends up making the whole world blind.", author: "Mahatma Gandhi" },
  { text: "You miss one hundred percent of the shots you never take.", author: "Wayne Gretzky" },
  { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
  { text: "Do or do not, there is no try.", author: "Yoda" },
  { text: "What we know is a drop, what we do not know is an ocean.", author: "Isaac Newton" },
  { text: "I have a dream that one day this nation will rise up and live out the true meaning of its creed.", author: "Martin Luther King Jr." },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "In three words I can sum up everything I have learned about life: it goes on.", author: "Robert Frost" },
  { text: "To thine own self be true.", author: "William Shakespeare" },
  { text: "It does not do to dwell on dreams and forget to live.", author: "Albus Dumbledore" },
  { text: "The mind is everything. What you think you become.", author: "Buddha" },
  { text: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison" },
  { text: "I came, I saw, I conquered.", author: "Julius Caesar" },
  { text: "Hell is other people.", author: "Jean-Paul Sartre" },
  { text: "One cannot step twice in the same river.", author: "Heraclitus" },
  { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
  { text: "If you want to go fast, go alone. If you want to go far, go together.", author: "African Proverb" },
  { text: "To infinity and beyond.", author: "Buzz Lightyear" },
  { text: "May the Force be with you.", author: "Star Wars" },
  { text: "After all, tomorrow is another day.", author: "Scarlett O'Hara" },
  { text: "All we have to decide is what to do with the time that is given us.", author: "J.R.R. Tolkien" },
  { text: "I am no bird and no net ensnares me. I am a free human being with an independent will.", author: "Charlotte Bronte" },
  { text: "It is our choices that show what we truly are, far more than our abilities.", author: "Albus Dumbledore" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "There is nothing either good or bad but thinking makes it so.", author: "William Shakespeare" },
  { text: "We suffer more often in imagination than in reality.", author: "Seneca" },
  { text: "Fortune favors the bold.", author: "Virgil" },
  { text: "I have not failed. I have just found ten thousand ways that will not work.", author: "Thomas Edison" },
  { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The greatest wealth is to live content with little.", author: "Plato" },
  { text: "Science is organized knowledge. Wisdom is organized life.", author: "Immanuel Kant" },
  { text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche" },
  { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
  { text: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
  { text: "Hard times create strong men. Strong men create good times.", author: "G. Michael Hopf" },
  { text: "No one can make you feel inferior without your consent.", author: "Eleanor Roosevelt" },
  { text: "Whether you think you can or you think you cannot, you are right.", author: "Henry Ford" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
  { text: "The best time to plant a tree was twenty years ago. The second best time is now.", author: "Chinese Proverb" },
  { text: "What does not satisfy when we find it was not the thing we were desiring.", author: "C.S. Lewis" },
  { text: "Courage is not the absence of fear but the judgment that something else is more important than fear.", author: "Ambrose Redmoon" },
  { text: "Everything you can imagine is real.", author: "Pablo Picasso" },
  { text: "A man is but the product of his thoughts. What he thinks, he becomes.", author: "Mahatma Gandhi" },
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
  { text: "If you are going through hell, keep going.", author: "Winston Churchill" },
  { text: "It always seems impossible until it is done.", author: "Nelson Mandela" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin" },
  { text: "The energy of the mind is the essence of life.", author: "Aristotle" },
  { text: "Champions keep playing until they get it right.", author: "Billie Jean King" },
  { text: "I can resist everything except temptation.", author: "Oscar Wilde" },
  { text: "Those who dare to fail miserably can achieve greatly.", author: "John F. Kennedy" },
  { text: "We become what we contemplate.", author: "Plato" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { text: "Music expresses that which cannot be put into words.", author: "Victor Hugo" },
  { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
  { text: "You cannot shake hands with a clenched fist.", author: "Indira Gandhi" },
  { text: "With great power comes great responsibility.", author: "Uncle Ben" },
  { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
  { text: "Logic will get you from A to B. Imagination will take you everywhere.", author: "Albert Einstein" },
  { text: "The obstacle is the way.", author: "Marcus Aurelius" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { text: "We are all in the gutter, but some of us are looking at the stars.", author: "Oscar Wilde" }
];
