const QUOTES = [
  { text: "The only thing we have to fear is fear itself.", author: "Franklin D. Roosevelt" },
  { text: "To be or not to be, that is the question.", author: "William Shakespeare" },
  { text: "I think, therefore I am.", author: "Rene Descartes" },
  { text: "The unexamined life is not worth living.", author: "Socrates" },
  { text: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
  { text: "Knowledge is power.", author: "Francis Bacon" },
  { text: "Life is what happens when you are busy making other plans.", author: "John Lennon" },
  { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "The greatest glory in living lies not in never falling but in rising every time we fall.", author: "Nelson Mandela" },
  { text: "It is never too late to be what you might have been.", author: "George Eliot" },
  { text: "Be yourself. Everyone else is already taken.", author: "Oscar Wilde" },
  { text: "Two things are infinite: the universe and human stupidity.", author: "Albert Einstein" },
  { text: "Not all those who wander are lost.", author: "J.R.R. Tolkien" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
  { text: "Imagination is more important than knowledge.", author: "Albert Einstein" },
  { text: "Injustice anywhere is a threat to justice everywhere.", author: "Martin Luther King Jr." },
  { text: "Stay hungry, stay foolish.", author: "Steve Jobs" },
  { text: "The best way to predict the future is to invent it.", author: "Alan Kay" },
  { text: "A room without books is like a body without a soul.", author: "Marcus Tullius Cicero" },
  { text: "If you tell the truth you do not need a good memory.", author: "Mark Twain" },
  { text: "Float like a butterfly, sting like a bee.", author: "Muhammad Ali" },
  { text: "We are what we repeatedly do. Excellence is not an act but a habit.", author: "Aristotle" },
  { text: "The pen is mightier than the sword.", author: "Edward Bulwer-Lytton" },
  { text: "Darkness cannot drive out darkness, only light can do that.", author: "Martin Luther King Jr." },
  { text: "Where there is love there is life.", author: "Mahatma Gandhi" },
  { text: "An eye for an eye only ends up making the whole world blind.", author: "Mahatma Gandhi" },
  { text: "You miss one hundred percent of the shots you never take.", author: "Wayne Gretzky" },
  { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
  { text: "Do or do not, there is no try.", author: "Yoda" },
  { text: "What we know is a drop, what we do not know is an ocean.", author: "Isaac Newton" },
  { text: "I have a dream that one day this nation will rise up and live out the true meaning of its creed.", author: "Martin Luther King Jr." },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "In three words I can sum up everything I have learned about life: it goes on.", author: "Robert Frost" },
  { text: "To thine own self be true.", author: "William Shakespeare" },
  { text: "It does not do to dwell on dreams and forget to live.", author: "Albus Dumbledore" },
  { text: "The mind is everything. What you think you become.", author: "Buddha" },
  { text: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison" },
  { text: "I came, I saw, I conquered.", author: "Julius Caesar" },
  { text: "Hell is other people.", author: "Jean-Paul Sartre" },
  { text: "One cannot step twice in the same river.", author: "Heraclitus" },
  { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
  { text: "If you want to go fast, go alone. If you want to go far, go together.", author: "African Proverb" },
  { text: "To infinity and beyond.", author: "Buzz Lightyear" },
  { text: "May the Force be with you.", author: "Star Wars" },
  { text: "After all, tomorrow is another day.", author: "Scarlett O'Hara" },
  { text: "All we have to decide is what to do with the time that is given us.", author: "J.R.R. Tolkien" },
  { text: "I am no bird and no net ensnares me. I am a free human being with an independent will.", author: "Charlotte Bronte" },
  { text: "It is our choices that show what we truly are, far more than our abilities.", author: "Albus Dumbledore" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "There is nothing either good or bad but thinking makes it so.", author: "William Shakespeare" },
  { text: "We suffer more often in imagination than in reality.", author: "Seneca" },
  { text: "Fortune favors the bold.", author: "Virgil" },
  { text: "I have not failed. I have just found ten thousand ways that will not work.", author: "Thomas Edison" },
  { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The greatest wealth is to live content with little.", author: "Plato" },
  { text: "Science is organized knowledge. Wisdom is organized life.", author: "Immanuel Kant" },
  { text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche" },
  { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
  { text: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
  { text: "Hard times create strong men. Strong men create good times.", author: "G. Michael Hopf" },
  { text: "No one can make you feel inferior without your consent.", author: "Eleanor Roosevelt" },
  { text: "Whether you think you can or you think you cannot, you are right.", author: "Henry Ford" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
  { text: "The best time to plant a tree was twenty years ago. The second best time is now.", author: "Chinese Proverb" },
  { text: "What does not satisfy when we find it was not the thing we were desiring.", author: "C.S. Lewis" },
  { text: "Courage is not the absence of fear but the judgment that something else is more important than fear.", author: "Ambrose Redmoon" },
  { text: "Everything you can imagine is real.", author: "Pablo Picasso" },
  { text: "A man is but the product of his thoughts. What he thinks, he becomes.", author: "Mahatma Gandhi" },
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
  { text: "If you are going through hell, keep going.", author: "Winston Churchill" },
  { text: "It always seems impossible until it is done.", author: "Nelson Mandela" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin" },
  { text: "The energy of the mind is the essence of life.", author: "Aristotle" },
  { text: "Champions keep playing until they get it right.", author: "Billie Jean King" },
  { text: "I can resist everything except temptation.", author: "Oscar Wilde" },
  { text: "Those who dare to fail miserably can achieve greatly.", author: "John F. Kennedy" },
  { text: "We become what we contemplate.", author: "Plato" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { text: "Music expresses that which cannot be put into words.", author: "Victor Hugo" },
  { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
  { text: "You cannot shake hands with a clenched fist.", author: "Indira Gandhi" },
  { text: "With great power comes great responsibility.", author: "Uncle Ben" },
  { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
  { text: "Logic will get you from A to B. Imagination will take you everywhere.", author: "Albert Einstein" },
  { text: "The obstacle is the way.", author: "Marcus Aurelius" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { text: "We are all in the gutter, but some of us are looking at the stars.", author: "Oscar Wilde" },
  { text: "The only thing standing between you and your goal is the story you keep telling yourself.", author: "Jordan Belfort" },
  { text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
  { text: "The unexamined life is not worth living for a human being.", author: "Plato" },
  { text: "A people that elect corrupt politicians are not victims but accomplices.", author: "George Orwell" },
  { text: "In the end, we will remember not the words of our enemies, but the silence of our friends.", author: "Martin Luther King Jr." },
  { text: "I have nothing to offer but blood, toil, tears and sweat.", author: "Winston Churchill" },
  { text: "The truth is rarely pure and never simple.", author: "Oscar Wilde" },
  { text: "One child, one teacher, one book, one pen can change the world.", author: "Malala Yousafzai" },
  { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
  { text: "In the depth of winter, I finally learned that within me there lay an invincible summer.", author: "Albert Camus" },
  { text: "There is no greater agony than bearing an untold story inside you.", author: "Maya Angelou" },
  { text: "Nothing is impossible, the word itself says I am possible.", author: "Audrey Hepburn" },
  { text: "The greatest glory of living lies in never falling but in rising every time you fall.", author: "Ralph Waldo Emerson" },
  { text: "I learned that courage was not the absence of fear but the triumph over it.", author: "Nelson Mandela" },
  { text: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
  { text: "Many of life's failures are people who did not realize how close they were when they gave up.", author: "Thomas Edison" },
  { text: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth" },
  { text: "Love all, trust a few, do wrong to none.", author: "William Shakespeare" },
  { text: "It is better to be feared than loved, if you cannot be both.", author: "Niccolo Machiavelli" },
  { text: "The only thing necessary for the triumph of evil is for good men to do nothing.", author: "Edmund Burke" },
  { text: "Keep your face always toward the sunshine and shadows will fall behind you.", author: "Walt Whitman" },
  { text: "Whoever is happy will make others happy too.", author: "Anne Frank" },
  { text: "We must learn to live together as brothers or perish together as fools.", author: "Martin Luther King Jr." },
  { text: "Speak softly and carry a big stick.", author: "Theodore Roosevelt" },
  { text: "The buck stops here.", author: "Harry S. Truman" },
  { text: "Ask not what your country can do for you, ask what you can do for your country.", author: "John F. Kennedy" },
  { text: "Give me liberty or give me death.", author: "Patrick Henry" },
  { text: "Government of the people, by the people, for the people.", author: "Abraham Lincoln" },
  { text: "I have a dream.", author: "Martin Luther King Jr." },
  { text: "The ballot is stronger than the bullet.", author: "Abraham Lincoln" },
  { text: "History will be kind to me for I intend to write it.", author: "Winston Churchill" },
  { text: "We shall fight on the beaches. We shall never surrender.", author: "Winston Churchill" },
  { text: "The only thing we learn from history is that we learn nothing from history.", author: "Georg Wilhelm Friedrich Hegel" },
  { text: "Power tends to corrupt and absolute power corrupts absolutely.", author: "Lord Acton" },
  { text: "The measure of a man is what he does with power.", author: "Plato" },
  { text: "No man is good enough to govern another man without that other's consent.", author: "Abraham Lincoln" },
  { text: "The hottest places in hell are reserved for those who maintain neutrality in times of crisis.", author: "Dante Alighieri" },
  { text: "The world is a book and those who do not travel read only one page.", author: "Saint Augustine" },
  { text: "Strive not to be a success but rather to be of value.", author: "Albert Einstein" },
  { text: "The mind is its own place and in itself can make a heaven of hell or a hell of heaven.", author: "John Milton" },
  { text: "I know that I know nothing.", author: "Socrates" },
  { text: "Man is condemned to be free.", author: "Jean-Paul Sartre" },
  { text: "God is dead. God remains dead. And we have killed him.", author: "Friedrich Nietzsche" },
  { text: "One must imagine Sisyphus happy.", author: "Albert Camus" },
  { text: "Happiness depends upon ourselves.", author: "Aristotle" },
  { text: "Entities should not be multiplied without necessity.", author: "William of Ockham" },
  { text: "The life of man is solitary, poor, nasty, brutish, and short.", author: "Thomas Hobbes" },
  { text: "I think, therefore I exist.", author: "Rene Descartes" },
  { text: "Whereof one cannot speak, thereof one must be silent.", author: "Ludwig Wittgenstein" },
  { text: "The greatest happiness of the greatest number is the foundation of morals.", author: "Jeremy Bentham" },
  { text: "Liberty consists in doing what one desires.", author: "John Stuart Mill" },
  { text: "Out of the crooked timber of humanity no straight thing was ever made.", author: "Immanuel Kant" },
  { text: "Imagination is the beginning of creation.", author: "George Bernard Shaw" },
  { text: "Do not go gentle into that good night.", author: "Dylan Thomas" },
  { text: "I wandered lonely as a cloud.", author: "William Wordsworth" },
  { text: "It was the best of times, it was the worst of times.", author: "Charles Dickens" },
  { text: "All happy families are alike. Each unhappy family is unhappy in its own way.", author: "Leo Tolstoy" },
  { text: "It is a truth universally acknowledged that a single man must be in want of a wife.", author: "Jane Austen" },
  { text: "Call me Ishmael.", author: "Herman Melville" },
  { text: "All animals are equal, but some animals are more equal than others.", author: "George Orwell" },
  { text: "Big Brother is watching you.", author: "George Orwell" },
  { text: "War is peace. Freedom is slavery. Ignorance is strength.", author: "George Orwell" },
  { text: "So it goes.", author: "Kurt Vonnegut" },
  { text: "The only people for me are the mad ones.", author: "Jack Kerouac" },
  { text: "All that is gold does not glitter.", author: "J.R.R. Tolkien" },
  { text: "Even the smallest person can change the course of the future.", author: "J.R.R. Tolkien" },
  { text: "There is some good in this world, and it is worth fighting for.", author: "J.R.R. Tolkien" },
  { text: "It is only with the heart that one can see rightly.", author: "Antoine de Saint-Exupery" },
  { text: "Beware; for I am fearless, and therefore powerful.", author: "Mary Shelley" },
  { text: "Whatever our souls are made of, his and mine are the same.", author: "Emily Bronte" },
  { text: "Brave new world, that has such people in it.", author: "William Shakespeare" },
  { text: "Shall I compare thee to a summer's day.", author: "William Shakespeare" },
  { text: "We know what we are but know not what we may be.", author: "William Shakespeare" },
  { text: "The lady doth protest too much, methinks.", author: "William Shakespeare" },
  { text: "Brevity is the soul of wit.", author: "William Shakespeare" },
  { text: "All the world's a stage, and all the men and women merely players.", author: "William Shakespeare" },
  { text: "Parting is such sweet sorrow.", author: "William Shakespeare" },
  { text: "Some are born great, some achieve greatness, and some have greatness thrust upon them.", author: "William Shakespeare" },
  { text: "The course of true love never did run smooth.", author: "William Shakespeare" },
  { text: "Better three hours too soon than a minute too late.", author: "William Shakespeare" },
  { text: "Time flies over us but leaves its shadow behind.", author: "Nathaniel Hawthorne" },
  { text: "The reports of my death are greatly exaggerated.", author: "Mark Twain" },
  { text: "Whenever you find yourself on the side of the majority, it is time to pause and reflect.", author: "Mark Twain" },
  { text: "Get your facts first and then you can distort them as much as you please.", author: "Mark Twain" },
  { text: "An archaeologist is the best husband a woman can have. The older she gets the more interested he is in her.", author: "Agatha Christie" },
  { text: "A lie gets halfway around the world before the truth puts on its boots.", author: "Mark Twain" },
  { text: "Travel is fatal to prejudice, bigotry, and narrow-mindedness.", author: "Mark Twain" },
  { text: "Never put off till tomorrow what may be done day after tomorrow just as well.", author: "Mark Twain" },
  { text: "Gravitation is not responsible for people falling in love.", author: "Albert Einstein" },
  { text: "The important thing is not to stop questioning. Curiosity has its own reason for existing.", author: "Albert Einstein" },
  { text: "Science without religion is lame, religion without science is blind.", author: "Albert Einstein" },
  { text: "Look deep into nature, and then you will understand everything better.", author: "Albert Einstein" },
  { text: "Peace cannot be kept by force. It can only be achieved by understanding.", author: "Albert Einstein" },
  { text: "Life is like riding a bicycle. To keep your balance you must keep moving.", author: "Albert Einstein" },
  { text: "Somewhere, something incredible is waiting to be known.", author: "Carl Sagan" },
  { text: "The cosmos is within us. We are made of star stuff.", author: "Carl Sagan" },
  { text: "For small creatures such as we, the vastness is bearable only through love.", author: "Carl Sagan" },
  { text: "We are a way for the cosmos to know itself.", author: "Carl Sagan" },
  { text: "Extraordinary claims require extraordinary evidence.", author: "Carl Sagan" },
  { text: "However difficult life may seem, there is always something you can do and succeed at.", author: "Stephen Hawking" },
  { text: "Intelligence is the ability to adapt to change.", author: "Stephen Hawking" },
  { text: "We are just an advanced breed of monkeys on a minor planet of a very average star.", author: "Stephen Hawking" },
  { text: "Nothing in life is to be feared, it is only to be understood.", author: "Marie Curie" },
  { text: "Be less curious about people and more curious about ideas.", author: "Marie Curie" },
  { text: "One never notices what has been done. One can only see what remains to be done.", author: "Marie Curie" },
  { text: "If I have seen further it is by standing on the shoulders of giants.", author: "Isaac Newton" },
  { text: "Measure what is measurable, and make measurable what is not so.", author: "Galileo Galilei" },
  { text: "I do not feel obliged to believe that the same God who gave us sense gave us intellect.", author: "Galileo Galilei" },
  { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
  { text: "Either write something worth reading or do something worth writing.", author: "Benjamin Franklin" },
  { text: "By failing to prepare, you are preparing to fail.", author: "Benjamin Franklin" },
  { text: "Never leave that till tomorrow which you can do today.", author: "Benjamin Franklin" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "Honesty is the first chapter in the book of wisdom.", author: "Thomas Jefferson" },
  { text: "In matters of style, swim with the current. In matters of principle, stand like a rock.", author: "Thomas Jefferson" },
  { text: "The harder I work, the luckier I get.", author: "Samuel Goldwyn" },
  { text: "Your time is limited, so do not waste it living someone else's life.", author: "Steve Jobs" },
  { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs" },
  { text: "Design is not just what it looks like. Design is how it works.", author: "Steve Jobs" },
  { text: "Move fast and break things.", author: "Mark Zuckerberg" },
  { text: "The biggest risk is not taking any risk.", author: "Mark Zuckerberg" },
  { text: "Done is better than perfect.", author: "Sheryl Sandberg" },
  { text: "If you are not embarrassed by the first version of your product, you launched too late.", author: "Reid Hoffman" },
  { text: "The best minds of my generation are thinking about how to make people click ads.", author: "Jeff Hammerbacher" },
  { text: "Your most unhappy customers are your greatest source of learning.", author: "Bill Gates" },
  { text: "If you cannot make it good, at least make it look good.", author: "Bill Gates" },
  { text: "Success is a lousy teacher. It seduces smart people into thinking they cannot lose.", author: "Bill Gates" },
  { text: "Risk more than others think is safe. Dream more than others think is practical.", author: "Howard Schultz" },
  { text: "The way I see it, if you want the rainbow you gotta put up with the rain.", author: "Dolly Parton" },
  { text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey" },
  { text: "Winners never quit and quitters never win.", author: "Vince Lombardi" },
  { text: "Perfection is not attainable but if we chase it we can catch excellence.", author: "Vince Lombardi" },
  { text: "The price of greatness is responsibility.", author: "Winston Churchill" },
  { text: "It is hard to fail but it is worse never to have tried to succeed.", author: "Theodore Roosevelt" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "Believe you can and you are halfway there.", author: "Theodore Roosevelt" },
  { text: "The man who does not read has no advantage over the man who cannot read.", author: "Mark Twain" },
  { text: "You can never cross the ocean until you have the courage to lose sight of the shore.", author: "Christopher Columbus" },
  { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
  { text: "What you get by achieving your goals is not as important as what you become.", author: "Zig Ziglar" },
  { text: "People often say that motivation does not last. Neither does bathing. That is why we recommend it daily.", author: "Zig Ziglar" },
  { text: "The best revenge is massive success.", author: "Frank Sinatra" },
  { text: "I did it my way.", author: "Frank Sinatra" },
  { text: "In the end, it is not the years in your life that count. It is the life in your years.", author: "Abraham Lincoln" },
  { text: "Nearly all men can stand adversity. If you want to test his character, give him power.", author: "Abraham Lincoln" },
  { text: "Whatever you are, be a good one.", author: "Abraham Lincoln" },
  { text: "Better to remain silent and be thought a fool than to speak and remove all doubt.", author: "Abraham Lincoln" },
  { text: "A house divided against itself cannot stand.", author: "Abraham Lincoln" },
  { text: "Here's to the crazy ones. The misfits. The rebels. The troublemakers.", author: "Apple Inc." },
  { text: "Think different.", author: "Apple Inc." },
  { text: "Just do it.", author: "Nike" },
  { text: "Houston, we have a problem.", author: "Apollo 13" },
  { text: "That is one small step for man, one giant leap for mankind.", author: "Neil Armstrong" },
  { text: "The Earth is the cradle of humanity but mankind cannot stay in the cradle forever.", author: "Konstantin Tsiolkovsky" },
  { text: "Toto, I have a feeling we are not in Kansas anymore.", author: "Dorothy, Wizard of Oz" },
  { text: "Here's looking at you, kid.", author: "Casablanca" },
  { text: "I am going to make him an offer he cannot refuse.", author: "The Godfather" },
  { text: "You talking to me.", author: "Taxi Driver" },
  { text: "Life is like a box of chocolates. You never know what you are gonna get.", author: "Forrest Gump" },
  { text: "There is no place like home.", author: "Dorothy, Wizard of Oz" },
  { text: "To be great is to be misunderstood.", author: "Ralph Waldo Emerson" },
  { text: "What lies behind us and what lies ahead of us are tiny matters compared to what lives within us.", author: "Henry David Thoreau" },
  { text: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau" },
  { text: "Our life is frittered away by detail. Simplify, simplify.", author: "Henry David Thoreau" },
  { text: "Rather than love, than money, than fame, give me truth.", author: "Henry David Thoreau" },
  { text: "Do not count the days, make the days count.", author: "Muhammad Ali" },
  { text: "He who is not courageous enough to take risks will accomplish nothing in life.", author: "Muhammad Ali" },
  { text: "I am the greatest. I said that even before I knew I was.", author: "Muhammad Ali" },
  { text: "It is not the size of the dog in the fight, it is the size of the fight in the dog.", author: "Mark Twain" },
  { text: "Hard work beats talent when talent does not work hard.", author: "Tim Notke" },
  { text: "The more I practice, the luckier I get.", author: "Gary Player" },
  { text: "It ain't over till it's over.", author: "Yogi Berra" },
  { text: "When you come to a fork in the road, take it.", author: "Yogi Berra" },
  { text: "You can observe a lot by just watching.", author: "Yogi Berra" },
  { text: "Baseball is ninety percent mental and the other half is physical.", author: "Yogi Berra" },
  { text: "Gold medals are not really made of gold. They are made of sweat and grit.", author: "Dan Gable" },
  { text: "Age is no barrier. It is a limitation you put on your mind.", author: "Jackie Joyner-Kersee" },
  { text: "The more difficult the victory, the greater the happiness in winning.", author: "Pele" },
  { text: "I have always believed that if you put in the work, the results will come.", author: "Michael Jordan" },
  { text: "I can accept failure. Everyone fails at something. But I cannot accept not trying.", author: "Michael Jordan" },
  { text: "Some people want it to happen. Some wish it would happen. Others make it happen.", author: "Michael Jordan" },
  { text: "Talent wins games but teamwork and intelligence win championships.", author: "Michael Jordan" },
  { text: "The man who has no imagination has no wings.", author: "Muhammad Ali" },
  { text: "A smooth sea never made a skilled sailor.", author: "Franklin D. Roosevelt" },
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { text: "The nail that sticks out gets hammered down.", author: "Japanese Proverb" },
  { text: "A journey of a thousand miles must begin with a single step.", author: "Chinese Proverb" },
  { text: "When the student is ready, the teacher will appear.", author: "Buddhist Proverb" },
  { text: "A wise man makes his own decisions. An ignorant man follows public opinion.", author: "Chinese Proverb" },
  { text: "The frog in the well knows nothing of the great ocean.", author: "Japanese Proverb" },
  { text: "Vision without action is a daydream. Action without vision is a nightmare.", author: "Japanese Proverb" },
  { text: "Give a man a fish and you feed him for a day. Teach him to fish and you feed him for life.", author: "Chinese Proverb" },
  { text: "An army of sheep led by a lion can defeat an army of lions led by a sheep.", author: "African Proverb" },
  { text: "A bird does not sing because it has an answer. It sings because it has a song.", author: "Chinese Proverb" },
  { text: "He who asks is a fool for five minutes. He who does not ask remains a fool forever.", author: "Chinese Proverb" },
  { text: "Still waters run deep.", author: "English Proverb" },
  { text: "What is coming is better than what is gone.", author: "Arabic Proverb" },
  { text: "Where there is a will, there is a way.", author: "English Proverb" },
  { text: "Every saint has a past, and every sinner has a future.", author: "Oscar Wilde" },
  { text: "Experience is simply the name we give our mistakes.", author: "Oscar Wilde" },
  { text: "Always forgive your enemies. Nothing annoys them so much.", author: "Oscar Wilde" },
  { text: "A cynic is a man who knows the price of everything and the value of nothing.", author: "Oscar Wilde" },
  { text: "Life imitates art far more than art imitates life.", author: "Oscar Wilde" },
  { text: "An idea that is not dangerous is unworthy of being called an idea at all.", author: "Oscar Wilde" },
  { text: "Hope is the thing with feathers that perches in the soul.", author: "Emily Dickinson" },
  { text: "Because I could not stop for Death, he kindly stopped for me.", author: "Emily Dickinson" },
  { text: "Tell all the truth but tell it slant.", author: "Emily Dickinson" },
  { text: "Forever is composed of nows.", author: "Emily Dickinson" },
  { text: "The road not taken has made all the difference.", author: "Robert Frost" },
  { text: "Good fences make good neighbors.", author: "Robert Frost" },
  { text: "Nothing gold can stay.", author: "Robert Frost" },
  { text: "Freedom lies in being bold.", author: "Robert Frost" },
  { text: "Poetry is when an emotion has found its thought and the thought has found words.", author: "Robert Frost" },
  { text: "I took the one less traveled by, and that has made all the difference.", author: "Robert Frost" },
  { text: "The wound is the place where the light enters you.", author: "Rumi" },
  { text: "What you seek is seeking you.", author: "Rumi" },
  { text: "Let yourself be silently drawn by the strange pull of what you really love.", author: "Rumi" },
  { text: "Yesterday I was clever so I wanted to change the world. Today I am wise so I am changing myself.", author: "Rumi" },
  { text: "Raise your words, not voice. It is rain that grows flowers, not thunder.", author: "Rumi" },
  { text: "You were born with wings. Why prefer to crawl through life.", author: "Rumi" },
  { text: "The lion does not turn around when a small dog barks.", author: "African Proverb" },
  { text: "No pressure, no diamonds.", author: "Thomas Carlyle" },
  { text: "It is not enough to have a good mind. The main thing is to use it well.", author: "Rene Descartes" },
  { text: "The greatest weapon against stress is our ability to choose one thought over another.", author: "William James" },
  { text: "Begin at the beginning and go on till you come to the end, then stop.", author: "Lewis Carroll" },
  { text: "Why, sometimes I have believed as many as six impossible things before breakfast.", author: "Lewis Carroll" },
  { text: "Curiouser and curiouser.", author: "Lewis Carroll" },
  { text: "We are all mad here.", author: "Lewis Carroll" },
  { text: "If you do not know where you are going, any road will get you there.", author: "Lewis Carroll" },
  { text: "The only way out of the labyrinth of suffering is to forgive.", author: "John Green" },
  { text: "Not all who wander are lost, but I sure am.", author: "Unknown" },
  { text: "Stars cannot shine without darkness.", author: "D.T. Suzuki" },
  { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "First they ignore you, then they laugh at you, then they fight you, then you win.", author: "Mahatma Gandhi" },
  { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
  { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi" },
  { text: "The weak can never forgive. Forgiveness is the attribute of the strong.", author: "Mahatma Gandhi" }
];
