#!/usr/bin/env node
// Comprehensive puzzle fixer:
// 1. Fix miscategorized words in groups
// 2. Fix word fragments
// 3. Replace ALL bad decoys with category-relevant alternatives
const fs = require('fs');
const vm = require('vm');
const src = fs.readFileSync(__dirname + '/puzzles.js', 'utf8');
const sb = {};
vm.runInNewContext(src.replace('const PUZZLES', 'var PUZZLES'), sb);
const PUZZLES = sb.PUZZLES;

// ── 1. CATEGORY POOLS ──────────────────────────────────────────────────
// For each category, extra words that COULD belong but aren't in the puzzle.
// Used to generate plausible decoys. Each pool has many entries to avoid reuse.
const CAT_POOL = {
  // ANIMALS
  "African animals": ["HYENA","WARTHOG","IMPALA","KUDU","WILDEBEEST","OKAPI","SPRINGBOK","MEERKAT","JACKAL","BABOON","CHEETAH","PANGOLIN"],
  "Antarctic animals": ["ALBATROSS","PETREL","SKUA","SEAL","KRILL","ORCA","NARWHAL","WALRUS"],
  "Australian animals": ["QUOKKA","WOMBAT","ECHIDNA","BILBY","NUMBAT","DINGO","CASSOWARY","PLATYPUS","WALLABY","BANDICOOT"],
  "Amphibians": ["NEWT","TOAD","FROG","SALAMANDER","CAECILIAN","AXE","SIREN","MUDPUPPY"],
  "Baby animals": ["KITTEN","PUPPY","FOAL","LAMB","JOEY","CALF","FAWN","GOSLING","DUCKLING","PIGLET","CUB","CHICK","KIT"],
  "Bamboo-eating animals": ["PANDA","GORILLA","LEMUR","OKAPI","ELEPHANT","CHIMPANZEE"],
  "Bats": ["PIPISTRELLE","HORSESHOE","FRUIT BAT","VAMPIRE BAT","FLYING FOX","MYOTIS","MEGABAT"],
  "Bears": ["GRIZZLY","POLAR","KODIAK","PANDA","SUN BEAR","KERMODE","MOON","SPECTACLED","SLOTH BEAR"],
  "Types of bear": ["GRIZZLY","POLAR","KODIAK","PANDA","SUN BEAR","KERMODE","MOON","SPECTACLED","SLOTH BEAR"],
  "Birds": ["SPARROW","ROBIN","FALCON","CRANE","HERON","MAGPIE","WREN","FINCH","SWIFT","LARK","STARLING","OSPREY"],
  "Canines": ["WOLF","JACKAL","COYOTE","DINGO","FOX","HYENA","FENNEC"],
  "Cat breeds": ["PERSIAN","SIAMESE","BENGAL","RAGDOLL","SPHYNX","ABYSSINIAN","BURMESE","MANX","BIRMAN"],
  "Cartoon cats": ["GARFIELD","SYLVESTER","TOM","FELIX","HEATHCLIFF","FIGARO","CHESHIRE"],
  "Cartoon dogs": ["PLUTO","SNOOPY","SCOOBY","GOOFY","ASTRO","ODIE","CLIFFORD"],
  "Cephalopods": ["SQUID","OCTOPUS","CUTTLEFISH","NAUTILUS","AMMONITE","KRAKEN"],
  "Clam varieties": ["QUAHOG","GEODUCK","RAZOR","LITTLENECK","CHERRYSTONE","COCKLE","STEAMER"],
  "Coral reef fish": ["CLOWNFISH","TANG","ANGELFISH","PARROTFISH","DAMSELFISH","WRASSE","GOBY","GROUPER"],
  "Coral types": ["BRAIN","STAGHORN","FAN","ELKHORN","PILLAR","FIRE","TABLE","MUSHROOM CORAL"],
  "Crustaceans": ["LOBSTER","CRAB","SHRIMP","BARNACLE","PRAWN","KRILL","CRAWFISH","WOODLOUSE"],
  "Deer species": ["MOOSE","ELK","CARIBOU","REINDEER","MULE DEER","ROE","FALLOW","MUNTJAC","SIKA","AXIS","SAMBAR"],
  "Diving birds": ["CORMORANT","GANNET","KINGFISHER","PUFFIN","GREBE","LOON","MURRE","AUK","PELICAN"],
  "Dog breeds": ["POODLE","BOXER","BEAGLE","COLLIE","DALMATIAN","RETRIEVER","TERRIER","BULLDOG","HUSKY","CORGI","SETTER","SPANIEL"],
  "Double-letter animals": ["LLAMA","POODLE","RACCOON","AARDVARK","BUFFALO","BASS","JELLYFISH","PARROT"],
  "Ducks": ["MALLARD","TEAL","EIDER","POCHARD","GADWALL","PINTAIL","WIGEON","SHOVELER","MERGANSER"],
  "Eagles": ["BALD","GOLDEN","HARPY","MARTIAL","STEPPE","BOOTED","CROWNED","FISH EAGLE"],
  "Falcons": ["PEREGRINE","KESTREL","MERLIN","GYRFALCON","HOBBY","LANNER","SAKER","PRAIRIE"],
  "Ferns": ["MAIDENHAIR","BRACKEN","BOSTON","STAGHORN FERN","ROYAL","SWORD","OSTRICH","BIRD NEST"],
  "Fish": ["TROUT","SALMON","BASS","PIKE","PERCH","MARLIN","TUNA","SWORDFISH","MACKEREL","COD","HALIBUT","STURGEON"],
  "Freshwater fish": ["TROUT","BASS","PIKE","PERCH","CATFISH","CARP","WALLEYE","BLUEGILL","CRAPPIE"],
  "River fish": ["TROUT","BASS","PIKE","PERCH","CATFISH","CARP","SALMON","STURGEON","CHUB","BARBEL"],
  "Frog species": ["BULLFROG","TREE FROG","POISON DART","LEOPARD FROG","SPRING PEEPER","GLASS FROG","RED-EYED"],
  "Hound breeds": ["BASSET","BLOODHOUND","GREYHOUND","WHIPPET","BEAGLE","FOXHOUND","WOLFHOUND","SALUKI","BORZOI"],
  "Insects": ["ANT","BEETLE","MOTH","CRICKET","FIREFLY","MANTIS","WASP","HORNET","CICADA","WEEVIL","APHID","LOCUST"],
  "Marsupials": ["KOALA","OPOSSUM","WALLABY","QUOKKA","WOMBAT","BANDICOOT","BILBY","NUMBAT","POTOROO"],
  "Ocean creatures": ["OCTOPUS","STARFISH","JELLYFISH","SEA URCHIN","SEAHORSE","DOLPHIN","WHALE","MANTA RAY","CORAL","MANATEE","NAUTILUS"],
  "Owls": ["BARN OWL","SNOWY","EAGLE OWL","SCREECH","GREAT HORNED","TAWNY","BURROWING","ELF OWL","BARRED"],
  "Parrots": ["MACAW","COCKATOO","BUDGIE","LOVEBIRD","CONURE","LORIKEET","AMAZON","COCKATIEL","KAKAPO"],
  "Pelicans and relatives": ["PELICAN","CORMORANT","GANNET","BOOBY","FRIGATE BIRD","ANHINGA","TROPICBIRD"],
  "Penguins": ["EMPEROR","KING","CHINSTRAP","GENTOO","MACARONI","ADELIE","ROCKHOPPER","FAIRY"],
  "Pigeons and doves": ["ROCK DOVE","TURTLE DOVE","MOURNING DOVE","WOOD PIGEON","STOCK DOVE","HOMING","FANTAIL"],
  "Primates": ["GORILLA","CHIMPANZEE","ORANGUTAN","GIBBON","LEMUR","TARSIER","MACAQUE","MARMOSET","CAPUCHIN","BABOON","MANDRILL"],
  "Raptor birds": ["EAGLE","HAWK","FALCON","OSPREY","KITE","VULTURE","HARRIER","BUZZARD","CONDOR"],
  "Raptors": ["EAGLE","HAWK","FALCON","OSPREY","KITE","VULTURE","HARRIER","BUZZARD","CONDOR"],
  "Reptiles": ["GECKO","IGUANA","CHAMELEON","COBRA","PYTHON","TORTOISE","CROCODILE","MONITOR","SKINK"],
  "Retriever breeds": ["GOLDEN","LABRADOR","CHESAPEAKE","FLAT-COAT","CURLY-COAT","NOVA SCOTIA"],
  "Rodents": ["HAMSTER","GERBIL","MOUSE","RAT","SQUIRREL","CHINCHILLA","CAPYBARA","PORCUPINE","BEAVER","GUINEA PIG"],
  "Salamanders": ["HELLBENDER","MUDPUPPY","CAECILIAN","AXOLOTL","FIRE SALAMANDER","TIGER SALAMANDER","SPOTTED"],
  "Seabirds": ["ALBATROSS","PETREL","PUFFIN","GANNET","TERN","SKUA","SHEARWATER","FULMAR","BOOBY"],
  "Sharks": ["HAMMERHEAD","BULL","TIGER","MAKO","NURSE","THRESHER","WHALE SHARK","REEF","BLUE","LEMON","BASKING","GREAT WHITE"],
  "Shellfish": ["MUSSEL","OYSTER","CLAM","SCALLOP","ABALONE","WHELK","CONCH","COCKLE","PERIWINKLE"],
  "Songbirds": ["NIGHTINGALE","THRUSH","WARBLER","ROBIN","FINCH","WREN","LARK","CANARY","BUNTING"],
  "Sushi fish": ["TUNA","SALMON","YELLOWTAIL","EEL","MACKEREL","SNAPPER","SHRIMP","OCTOPUS"],
  "Terrier breeds": ["YORKSHIRE","SCOTTISH","BULL TERRIER","JACK RUSSELL","CAIRN","WESTIE","AIREDALE","FOX TERRIER"],
  "Tropical birds": ["TOUCAN","PARROT","FLAMINGO","MACAW","COCKATOO","HORNBILL","QUETZAL","LORIKEET"],
  "Whale species": ["HUMPBACK","BELUGA","NARWHAL","ORCA","MINKE","FIN WHALE","BOWHEAD","RIGHT WHALE","SPERM WHALE"],
  "Whales": ["HUMPBACK","BELUGA","NARWHAL","ORCA","MINKE","FIN WHALE","BOWHEAD","RIGHT WHALE","SPERM WHALE"],
  "Wild cats": ["LYNX","OCELOT","BOBCAT","COUGAR","SERVAL","CARACAL","MARGAY","JAGUAR","PANTHER","CHEETAH"],
  "Zoo animals": ["GIRAFFE","ELEPHANT","LION","TIGER","GORILLA","HIPPO","ZEBRA","RHINO","PANDA","FLAMINGO"],

  // FOOD & DRINK
  "Apples": ["FUJI","GALA","GRANNY SMITH","HONEYCRISP","BRAEBURN","MCINTOSH","PINK LADY","CORTLAND","JONAGOLD"],
  "Bagel flavors": ["SESAME","POPPY","EVERYTHING","CINNAMON RAISIN","ONION","GARLIC","PLAIN","PUMPERNICKEL","SALT"],
  "Baked goods": ["SCONE","MUFFIN","CROISSANT","BRIOCHE","DANISH","ECLAIR","STRUDEL","TURNOVER","BISCUIT"],
  "Beans": ["PINTO","KIDNEY","NAVY","BLACK","LIMA","FAVA","CANNELLINI","CHICKPEA","LENTIL","MUNG"],
  "Types of bean": ["PINTO","KIDNEY","NAVY","BLACK","LIMA","FAVA","CANNELLINI","CHICKPEA","LENTIL","MUNG"],
  "Berries": ["BLUEBERRY","RASPBERRY","STRAWBERRY","BLACKBERRY","CRANBERRY","GOOSEBERRY","ELDERBERRY","BOYSENBERRY","MULBERRY","LINGONBERRY"],
  "Berries (true botanical)": ["GRAPE","BANANA","TOMATO","AVOCADO","KIWI","GOOSEBERRY","CURRANT","ELDERBERRY"],
  "Breads": ["SOURDOUGH","PUMPERNICKEL","FOCACCIA","CIABATTA","BRIOCHE","CHALLAH","NAAN","PITA","BAGUETTE","RYE"],
  "Breakfast foods": ["WAFFLE","PANCAKE","BAGEL","CROISSANT","OATMEAL","GRANOLA","FRENCH TOAST","CEREAL","MUESLI","PORRIDGE"],
  "Brazilian dishes": ["FEIJOADA","COXINHA","PAVE","ACAI BOWL","BRIGADEIRO","MOQUECA","FAROFA","TAPIOCA"],
  "Butternut squash relatives": ["ACORN","SPAGHETTI","ZUCCHINI","PUMPKIN","KABOCHA","DELICATA","HUBBARD","PATTY PAN"],
  "Cacti": ["SAGUARO","BARREL","PRICKLY PEAR","CHOLLA","ORGAN PIPE","FISHHOOK","HEDGEHOG","PADDLE"],
  "Cactus types": ["SAGUARO","BARREL","PRICKLY PEAR","CHOLLA","ORGAN PIPE","FISHHOOK","HEDGEHOG","PADDLE"],
  "Cereals": ["CHEERIOS","WHEATIES","CORNFLAKES","FROOT LOOPS","GRANOLA","MUESLI","BRAN FLAKES","RICE KRISPIES"],
  "Charcuterie items": ["PROSCIUTTO","SALAMI","COPPA","BRESAOLA","MORTADELLA","PANCETTA","GUANCIALE","SOPPRESSATA"],
  "Cheeses": ["BRIE","GOUDA","CHEDDAR","FETA","GRUYERE","ROQUEFORT","MANCHEGO","HAVARTI","CAMEMBERT","PROVOLONE","MOZZARELLA"],
  "Cheeses of France": ["BRIE","CAMEMBERT","ROQUEFORT","COMTE","REBLOCHON","MUNSTER","EPOISSES","BEAUFORT","MORBIER"],
  "French cheeses": ["BRIE","CAMEMBERT","ROQUEFORT","COMTE","REBLOCHON","MUNSTER","EPOISSES","BEAUFORT","MORBIER"],
  "Italian cheeses": ["PARMESAN","MOZZARELLA","PECORINO","GORGONZOLA","FONTINA","RICOTTA","TALEGGIO","BURRATA","ASIAGO"],
  "Soft cheeses": ["BRIE","CAMEMBERT","RICOTTA","MASCARPONE","CHEVRE","BOURSIN","CREAM CHEESE","NEUFCHATEL"],
  "Types of cheese": ["BRIE","GOUDA","CHEDDAR","FETA","GRUYERE","ROQUEFORT","MANCHEGO","HAVARTI","CAMEMBERT"],
  "Chili varieties": ["HABANERO","SERRANO","POBLANO","ANCHO","GUAJILLO","CHIPOTLE","CAYENNE","BIRD'S EYE"],
  "Chinese dishes": ["KUNG PAO","MAPO TOFU","CHAR SIU","DIM SUM","HOT POT","CHOW MEIN","WONTONS","PEKING DUCK","CONGEE"],
  "Citrus fruits": ["LEMON","LIME","GRAPEFRUIT","TANGERINE","KUMQUAT","POMELO","CLEMENTINE","YUZU","BERGAMOT","MANDARIN"],
  "Cocktails": ["MARTINI","MANHATTAN","DAIQUIRI","MOJITO","NEGRONI","SIDECAR","GIN FIZZ","OLD FASHIONED","COSMOPOLITAN"],
  "Coffee drinks": ["LATTE","MOCHA","ESPRESSO","CORTADO","AMERICANO","CAPPUCCINO","MACCHIATO","FLAT WHITE","RISTRETTO"],
  "Coffee origins": ["COLOMBIAN","ETHIOPIAN","KENYAN","JAMAICAN","SUMATRA","KONA","GUATEMALAN","BRAZILIAN","YEMENI"],
  "Curry ingredients": ["TURMERIC","CUMIN","CORIANDER","CARDAMOM","FENUGREEK","GARAM MASALA","CHILI POWDER","GINGER"],
  "Dairy products": ["BUTTER","CREAM","YOGURT","MILK","CHEESE","WHEY","KEFIR","GHEE","SOUR CREAM","CURD"],
  "Desserts": ["TIRAMISU","CREME BRULEE","PANNA COTTA","SOUFFLE","MOUSSE","PARFAIT","TRIFLE","COBBLER","GALETTE"],
  "Dim sum items": ["HAR GOW","SIU MAI","CHAR SIU BAO","CHEUNG FUN","TURNIP CAKE","EGG TART","SESAME BALL","SPRING ROLL"],
  "Dips and sauces": ["HUMMUS","GUACAMOLE","TZATZIKI","SALSA","AIOLI","PESTO","RANCH","CHIMICHURRI","TAHINI"],
  "Dumpling types": ["PIEROGI","GYOZA","KNODEL","MOMO","MANDU","RAVIOLI","WONTON","PELMENI","EMPANADA"],
  "Egyptian foods": ["KOSHARI","FUL MEDAMES","MOLOKHIA","FALAFEL","MAHSHI","FATTOUSH","BASBOUSA","KONAFA"],
  "Ethiopian foods": ["INJERA","WAT","KITFO","TIBS","SHIRO","DORO WAT","BEYAYNETU","FIRFIR"],
  "Flatbreads": ["NAAN","PITA","TORTILLA","ROTI","CHAPATI","LAVASH","FOCACCIA","AREPA","PARATHA","INJERA"],
  "French pastries": ["ECLAIR","MILLE-FEUILLE","MACARON","CROISSANT","PROFITEROLE","TARTE TATIN","RELIGIEUSE","PARIS-BREST"],
  "Fruits": ["MANGO","PAPAYA","GUAVA","LYCHEE","KIWI","PINEAPPLE","PASSION FRUIT","POMEGRANATE","FIG","DATE","PERSIMMON"],
  "German foods": ["BRATWURST","SCHNITZEL","PRETZEL","SAUERKRAUT","STRUDEL","SAUERBRATEN","KNODEL","SPATZLE","CURRYWURST"],
  "Grains": ["WHEAT","BARLEY","QUINOA","MILLET","SORGHUM","SPELT","FARRO","KAMUT","BUCKWHEAT","AMARANTH"],
  "Grape varieties": ["MERLOT","CABERNET","PINOT","RIESLING","CHARDONNAY","SYRAH","ZINFANDEL","MALBEC","GRENACHE"],
  "Hawaiian foods": ["POKE","LOCO MOCO","SPAM MUSUBI","KALUA PIG","HAUPIA","LAULAU","POI","MALASADA","ACAI"],
  "Herbs": ["BASIL","THYME","ROSEMARY","OREGANO","DILL","CILANTRO","PARSLEY","SAGE","MINT","CHIVE","TARRAGON","MARJORAM"],
  "Herbs for cooking": ["BASIL","THYME","ROSEMARY","OREGANO","DILL","CILANTRO","PARSLEY","SAGE","MINT","CHIVE"],
  "Ice cream flavors": ["VANILLA","CHOCOLATE","STRAWBERRY","PISTACHIO","MINT CHIP","ROCKY ROAD","BUTTER PECAN","COOKIE DOUGH"],
  "Indian breads": ["NAAN","ROTI","PARATHA","CHAPATI","PURI","DOSA","KULCHA","BHATURA","APPAM"],
  "Indian spices": ["TURMERIC","CUMIN","CARDAMOM","CORIANDER","FENUGREEK","CLOVE","SAFFRON","MUSTARD SEED","ASAFOETIDA"],
  "Indonesian foods": ["NASI GORENG","SATAY","RENDANG","GADO GADO","TEMPEH","BAKSO","SOTO","RAWON","GUDEG"],
  "Italian dishes": ["RISOTTO","LASAGNA","CARBONARA","TIRAMISU","OSSOBUCO","BRUSCHETTA","CAPRESE","MINESTRONE"],
  "Jamaican foods": ["JERK CHICKEN","ACKEE","CALLALOO","PATTY","BAMMY","ESCOVITCH","RUN DOWN","FESTIVAL"],
  "Japanese food": ["RAMEN","SASHIMI","TEMPURA","TONKATSU","OKONOMIYAKI","YAKITORI","UDON","ONIGIRI","MISO","EDAMAME"],
  "Japanese sweets": ["MOCHI","DANGO","DORAYAKI","TAIYAKI","YOKAN","DAIFUKU","MONAKA","CASTELLA","WARABI"],
  "Korean dishes": ["BIBIMBAP","KIMCHI","BULGOGI","JAPCHAE","TTEOKBOKKI","SAMGYEOPSAL","GALBI","SUNDUBU","GIMBAP"],
  "Lebanese dishes": ["TABBOULEH","FATTOUSH","KIBBEH","MANAKISH","SHAWARMA","LABNEH","BAKLAVA","HALLOUMI"],
  "Leafy greens": ["SPINACH","KALE","ARUGULA","ROMAINE","CHARD","WATERCRESS","ENDIVE","RADICCHIO","BOK CHOY","COLLARD"],
  "Legumes": ["LENTIL","CHICKPEA","PEA","PEANUT","SOYBEAN","ALFALFA","CLOVER","LUPIN","TAMARIND"],
  "Mediterranean herbs": ["OREGANO","THYME","ROSEMARY","BASIL","SAGE","MARJORAM","BAY LEAF","FENNEL","LAVENDER"],
  "Melon types": ["HONEYDEW","CANTALOUPE","WATERMELON","CASABA","CRENSHAW","GALIA","CANARY","SANTA CLAUS"],
  "Mexican food": ["TACO","ENCHILADA","BURRITO","TAMALE","QUESADILLA","POZOLE","CHILAQUILES","ELOTE","CHURRO"],
  "Middle Eastern foods": ["HUMMUS","FALAFEL","SHAWARMA","TABOULEH","BAKLAVA","KIBBEH","FATTOUSH","LABNEH","BABA GHANOUSH"],
  "Moroccan dishes": ["TAGINE","COUSCOUS","HARIRA","PASTILLA","MSEMEN","ZAALOUK","RFISSA","BISSARA","CHEBAKIA"],
  "Mushroom types": ["SHIITAKE","PORTOBELLO","CHANTERELLE","MOREL","OYSTER","PORCINI","ENOKI","MAITAKE","TRUFFLE"],
  "Mushrooms": ["SHIITAKE","PORTOBELLO","CHANTERELLE","MOREL","OYSTER","PORCINI","ENOKI","MAITAKE","TRUFFLE"],
  "Nut butters": ["PEANUT","ALMOND","CASHEW","HAZELNUT","PECAN","WALNUT","PISTACHIO","MACADAMIA","SUNFLOWER"],
  "Nuts": ["ALMOND","WALNUT","CASHEW","PISTACHIO","PECAN","HAZELNUT","MACADAMIA","FILBERT","CHESTNUT","BRAZIL NUT","PINE NUT"],
  "Olive oil grades": ["EXTRA VIRGIN","VIRGIN","REFINED","POMACE","COLD PRESSED","FIRST PRESS","LIGHT","LAMPANTE"],
  "Olives": ["KALAMATA","MANZANILLA","CASTELVETRANO","CERIGNOLA","NICOISE","GAETA","PICHOLINE","GORDAL"],
  "Pasta sauces": ["MARINARA","PESTO","ALFREDO","BOLOGNESE","ARRABBIATA","CARBONARA","PUTTANESCA","AMATRICIANA","VODKA"],
  "Pasta shapes": ["PENNE","RIGATONI","FUSILLI","ORZO","FARFALLE","LINGUINE","ROTINI","ORECCHIETTE","ZITI","CAVATAPPI"],
  "Types of pasta": ["PENNE","RIGATONI","FUSILLI","ORZO","FARFALLE","LINGUINE","ROTINI","SPAGHETTI","FETTUCCINE"],
  "Types of noodle": ["UDON","SOBA","RAMEN","RICE","GLASS","EGG","CELLOPHANE","LO MEIN","PAD THAI","PAPPARDELLE"],
  "Peppers": ["JALAPENO","HABANERO","SERRANO","POBLANO","BELL","CAYENNE","BIRD'S EYE","BANANA","ANAHEIM","SCOTCH BONNET"],
  "Types of pepper": ["JALAPENO","HABANERO","SERRANO","POBLANO","BELL","CAYENNE","BIRD'S EYE","BANANA","ANAHEIM"],
  "Peruvian foods": ["CEVICHE","LOMO SALTADO","AJI DE GALLINA","ANTICUCHO","CAUSA","PAPA A LA HUANCAINA","PICARONES"],
  "Pizza styles": ["NEAPOLITAN","DETROIT","NEW YORK","SICILIAN","CHICAGO","ROMAN","GRANDMA","MARGHERITA","STUFFED"],
  "Pizza toppings": ["PEPPERONI","MUSHROOM","OLIVE","SAUSAGE","ANCHOVY","ONION","PEPPER","PINEAPPLE","BASIL","JALAPENO"],
  "Polish foods": ["PIEROGI","BIGOS","KIELBASA","ZUREK","PLACEK","BARSZCZ","GOLABKI","KOPYTKA","MAKOWIEC"],
  "Root vegetables": ["CARROT","TURNIP","PARSNIP","BEET","RADISH","RUTABAGA","CELERY ROOT","YUCA","DAIKON","GINGER","TARO"],
  "Russian dishes": ["BORSCHT","BLINI","PELMENI","SHASHLIK","PIROZHKI","BEEF STROGANOFF","SOLYANKA","KASHA","OLIVIER"],
  "Salad greens": ["ROMAINE","ARUGULA","ENDIVE","RADICCHIO","FRISEE","BIBB","MESCLUN","ICEBERG","WATERCRESS"],
  "Types of lettuce": ["ROMAINE","BUTTERHEAD","ICEBERG","BIBB","LOOSELEAF","OAK LEAF","BATAVIA","FRISEE","RED LEAF"],
  "Salamis": ["GENOA","SOPRESSATA","FINOCCHIONA","FELINO","CACCIATORE","PEPPERONI","NDUJA","COTTO"],
  "Salmon preparations": ["SMOKED","GRAVLAX","SASHIMI","POACHED","TERIYAKI","CURED","BAKED","GRILLED","TARTARE"],
  "Types of salmon": ["CHINOOK","SOCKEYE","COHO","PINK","CHUM","ATLANTIC","KING","STEELHEAD"],
  "Sandwich types": ["CLUB","REUBEN","BLT","PANINI","GRINDER","PO BOY","CUBAN","MONTE CRISTO","MUFFULETTA"],
  "Sandwiches": ["CLUB","REUBEN","BLT","PANINI","GRINDER","PO BOY","CUBAN","MONTE CRISTO","MUFFULETTA"],
  "Sausage types": ["BRATWURST","KIELBASA","CHORIZO","ANDOUILLE","MERGUEZ","BOUDIN","CUMBERLAND","LINGUICA","WEISSWURST"],
  "Smoked meats": ["BRISKET","BACON","PASTRAMI","JERKY","KIPPER","ANDOUILLE","PANCETTA","PROSCIUTTO","GRAVLAX"],
  "Soup varieties": ["MINESTRONE","BISQUE","CHOWDER","CONSOMME","GAZPACHO","GUMBO","RAMEN","PHO","BOUILLABAISSE"],
  "Soups": ["MINESTRONE","BISQUE","CHOWDER","CONSOMME","GAZPACHO","GUMBO","RAMEN","PHO","BOUILLABAISSE"],
  "Spanish foods": ["PAELLA","GAZPACHO","TORTILLA","CHURRO","CROQUETA","FABADA","PIMIENTOS"],
  "Spanish tapas": ["PATATAS BRAVAS","CROQUETAS","GAMBAS AL AJILLO","JAMON","MANCHEGO","BOQUERONES","PIMIENTOS","ALBONDIGAS"],
  "Spices": ["CINNAMON","NUTMEG","CUMIN","PAPRIKA","SAFFRON","TURMERIC","CLOVE","CARDAMOM","GINGER","PEPPER","CORIANDER"],
  "Steak cuts": ["RIBEYE","SIRLOIN","FILET","T-BONE","PORTERHOUSE","FLANK","SKIRT","STRIP","TOMAHAWK","HANGER"],
  "Stews around the world": ["GOULASH","TAGINE","RATATOUILLE","CASSOULET","BOUILLABAISSE","CHILI","GUMBO","BURGOO","POZOLE"],
  "Succulents": ["ALOE","JADE","ECHEVERIA","SEDUM","AGAVE","SEMPERVIVUM","HAWORTHIA","CRASSULA"],
  "Sushi types": ["NIGIRI","MAKI","TEMAKI","SASHIMI","URAMAKI","CHIRASHI","INARI","GUNKAN"],
  "Sushi varieties": ["NIGIRI","MAKI","TEMAKI","SASHIMI","URAMAKI","CHIRASHI","INARI","GUNKAN"],
  "Tea varieties": ["EARL GREY","CHAMOMILE","OOLONG","MATCHA","DARJEELING","JASMINE","SENCHA","PU-ERH","ROOIBOS"],
  "Teas": ["EARL GREY","CHAMOMILE","OOLONG","MATCHA","DARJEELING","JASMINE","SENCHA","PU-ERH","ROOIBOS"],
  "Teas of the world": ["DARJEELING","SENCHA","ROOIBOS","MATE","CHAI","MATCHA","PU-ERH","CEYLON","ASSAM"],
  "Types of tea": ["EARL GREY","CHAMOMILE","OOLONG","MATCHA","DARJEELING","JASMINE","SENCHA","PU-ERH","ROOIBOS"],
  "Thai curries": ["GREEN","RED","YELLOW","MASSAMAN","PANANG","JUNGLE","KHAO SOI","KAENG SOM"],
  "Thai ingredients": ["LEMONGRASS","GALANGAL","KAFFIR LIME","FISH SAUCE","PALM SUGAR","TAMARIND","BASIL","CHILI"],
  "Tropical fruits": ["MANGO","PAPAYA","GUAVA","LYCHEE","PASSION FRUIT","DRAGON FRUIT","RAMBUTAN","STARFRUIT","JACKFRUIT"],
  "Turkish dishes": ["LAHMACUN","SIMIT","DONER","BAKLAVA","PIDE","KOFTE","MANTI","BOREK","ISKENDER","GOZLEME"],
  "Types of cake": ["SPONGE","BUNDT","ANGEL FOOD","POUND","CHIFFON","RED VELVET","BLACK FOREST","CARROT","CHEESECAKE"],
  "Types of honey": ["MANUKA","CLOVER","ACACIA","WILDFLOWER","BUCKWHEAT","ORANGE BLOSSOM","EUCALYPTUS","LAVENDER","SAGE"],
  "Types of rice": ["BASMATI","JASMINE","ARBORIO","WILD","BROWN","SUSHI","BOMBA","STICKY","CALROSE","FORBIDDEN"],
  "Types of tuna": ["BLUEFIN","YELLOWFIN","SKIPJACK","ALBACORE","BIGEYE","LONGFIN","TONGOL","BONITO"],
  "Types of vinegar": ["BALSAMIC","APPLE CIDER","RED WINE","WHITE WINE","RICE","MALT","SHERRY","CHAMPAGNE","DISTILLED"],
  "Types of wine": ["MERLOT","CABERNET","PINOT NOIR","CHARDONNAY","RIESLING","SYRAH","ZINFANDEL","MALBEC"],
  "Vegetables": ["BROCCOLI","CAULIFLOWER","ZUCCHINI","EGGPLANT","ASPARAGUS","ARTICHOKE","FENNEL","RADISH","TURNIP","OKRA"],
  "Vietnamese dishes": ["PHO","BANH MI","BUN CHA","GOI CUON","CAO LAU","COM TAM","BANH XEO","BUN BO HUE"],
  "Wine regions": ["BORDEAUX","BURGUNDY","CHAMPAGNE","TUSCANY","NAPA","RIOJA","BAROSSA","MARLBOROUGH","MOSEL"],
  "Wines by color": ["MERLOT","CHARDONNAY","ROSE","PINOT GRIGIO","CABERNET","RIESLING","SAUVIGNON BLANC","MALBEC"],

  // GEOGRAPHY
  "African countries": ["KENYA","GHANA","SENEGAL","MALI","CHAD","NIGER","TOGO","BENIN","GABON","RWANDA","UGANDA"],
  "Asian countries": ["LAOS","NEPAL","BHUTAN","BRUNEI","MYANMAR","MONGOLIA","CAMBODIA","VIETNAM","BANGLADESH"],
  "Capital cities": ["PARIS","TOKYO","CAIRO","LIMA","OSLO","BERN","QUITO","DHAKA","MINSK","RABAT","DOHA","RIYADH"],
  "World capitals": ["PARIS","TOKYO","CAIRO","LIMA","OSLO","BERN","QUITO","DHAKA","MINSK","RABAT","DOHA"],
  "Constellations": ["ORION","URSA MAJOR","CASSIOPEIA","DRACO","LYRA","AQUILA","CYGNUS","PEGASUS","ANDROMEDA"],
  "Countries in South America": ["BRAZIL","ARGENTINA","CHILE","COLOMBIA","PERU","ECUADOR","BOLIVIA","URUGUAY","PARAGUAY","VENEZUELA"],
  "Deserts": ["SAHARA","GOBI","KALAHARI","MOJAVE","ATACAMA","SONORAN","NEGEV","NAMIB","PATAGONIAN","TAKLAMAKAN"],
  "Famous bridges": ["BROOKLYN","GOLDEN GATE","TOWER","RIALTO","PONT NEUF","LONDON","MACKINAC","FORTH","SYDNEY HARBOUR"],
  "Famous canals": ["SUEZ","PANAMA","ERIE","GRAND","CORINTH","KIEL","AMSTERDAM","WELLAND","GOTA"],
  "Famous mountains": ["EVEREST","DENALI","KILIMANJARO","MATTERHORN","FUJI","ELBRUS","RAINIER","MONT BLANC"],
  "Famous towers": ["EIFFEL","BIG BEN","PISA","BABEL","CN TOWER","PETRONAS","BURJ KHALIFA","TOKYO TOWER","SEARS"],
  "Famous walls": ["BERLIN","GREAT WALL","WESTERN","HADRIAN'S","WALL STREET","KREMLIN","ANTONINE"],
  "Fictional islands": ["NEVERLAND","AVALON","SKULL ISLAND","TREASURE","JURASSIC","GILLIGAN'S","SHUTTER","THEMYSCIRA"],
  "Islands": ["MADAGASCAR","BORNEO","BALI","FIJI","CRETE","SARDINIA","CORSICA","SICILY","MALTA","TAHITI"],
  "Lakes": ["BAIKAL","TITICACA","VICTORIA","HURON","COMO","TAHOE","GENEVA","MALAWI","CHAD","ERIE","SUPERIOR"],
  "Mountain ranges": ["ANDES","ALPS","HIMALAYAS","ROCKIES","PYRENEES","CASCADES","ATLAS","URALS","APPALACHIAN","DOLOMITES"],
  "Oceans": ["PACIFIC","ATLANTIC","INDIAN","ARCTIC","SOUTHERN","ANTARCTIC"],
  "One-word countries": ["FRANCE","BRAZIL","JAPAN","ITALY","SPAIN","CHILE","PERU","CUBA","FIJI","IRAN","IRAQ","KENYA","CHAD","TOGO"],
  "Rivers": ["NILE","AMAZON","DANUBE","THAMES","SEINE","RHINE","GANGES","MISSISSIPPI","YANGTZE","MEKONG","VOLGA","TIGRIS"],
  "Tectonic plates": ["PACIFIC","EURASIAN","NAZCA","CARIBBEAN","PHILIPPINE","ARABIAN","SCOTIA","COCOS","JUAN DE FUCA"],
  "Volcanoes": ["VESUVIUS","KRAKATOA","ETNA","FUJI","PINATUBO","KILAUEA","OLYMPUS MONS","MAUNA LOA","STROMBOLI","TAMBORA"],

  // SCIENCE & NATURE
  "Chemical elements": ["GOLD","SILVER","COPPER","IRON","NEON","ARGON","XENON","HELIUM","COBALT","NICKEL","ZINC","TIN","LEAD"],
  "Clouds": ["CIRRUS","NIMBUS","STRATUS","CUMULUS","ALTO","CUMULONIMBUS","MAMMATUS","LENTICULAR"],
  "Types of cloud": ["CIRRUS","NIMBUS","STRATUS","CUMULUS","ALTO","CUMULONIMBUS","MAMMATUS","LENTICULAR"],
  "Types of clouds": ["CIRRUS","NIMBUS","STRATUS","CUMULUS","ALTO","CUMULONIMBUS","MAMMATUS","LENTICULAR"],
  "Fossils": ["AMMONITE","TRILOBITE","COPROLITE","AMBER","PETRIFIED WOOD","MEGALODON TOOTH","FERN FOSSIL","BELEMNITE"],
  "Gemstones": ["EMERALD","TOPAZ","OPAL","JADE","RUBY","SAPPHIRE","DIAMOND","AMETHYST","GARNET","PERIDOT","TURQUOISE","ONYX","CITRINE","AQUAMARINE"],
  "Metals": ["GOLD","SILVER","COPPER","IRON","PLATINUM","TITANIUM","BRONZE","STEEL","PEWTER","BRASS","CHROME","NICKEL"],
  "Minerals": ["QUARTZ","FELDSPAR","MICA","CALCITE","GYPSUM","TALC","FLUORITE","PYRITE","OBSIDIAN","JASPER","AGATE","TOPAZ"],
  "NASA missions": ["APOLLO","GEMINI","MERCURY","VOYAGER","PIONEER","CASSINI","JUNO","CURIOSITY","HUBBLE","ARTEMIS"],
  "Nobel Prize categories": ["PEACE","PHYSICS","CHEMISTRY","MEDICINE","LITERATURE","ECONOMICS"],
  "Planets": ["MERCURY","VENUS","MARS","JUPITER","SATURN","URANUS","NEPTUNE","EARTH","PLUTO"],
  "Planets visible to naked eye": ["MERCURY","VENUS","MARS","JUPITER","SATURN"],
  "Shapes": ["HEXAGON","PENTAGON","OCTAGON","RHOMBUS","TRAPEZOID","PARALLELOGRAM","ELLIPSE","CYLINDER"],
  "Things in space": ["ASTEROID","COMET","NEBULA","QUASAR","PULSAR","METEOR","SATELLITE","MOON","BLACK HOLE","GALAXY"],
  "Seashells": ["CONCH","COWRIE","NAUTILUS","SCALLOP","WHELK","ABALONE","COCKLE","MUREX","AUGER","LIMPET"],
  "Types of storms": ["HURRICANE","TORNADO","BLIZZARD","MONSOON","TYPHOON","CYCLONE","SQUALL","TEMPEST","DERECHO"],
  "Zodiac signs": ["ARIES","TAURUS","GEMINI","CANCER","LEO","VIRGO","LIBRA","SCORPIO","SAGITTARIUS","CAPRICORN","AQUARIUS","PISCES"],

  // GAMES, SPORTS & ENTERTAINMENT
  "Baseball terms": ["DUGOUT","BULLPEN","INFIELD","BUNT","STEAL","SHUTOUT","DOUBLE PLAY","FOUL","SLIDER","GROUNDER","FLY BALL"],
  "Board games": ["RISK","LIFE","SORRY","CLUE","MONOPOLY","SCRABBLE","CHECKERS","CHESS","BATTLESHIP","YAHTZEE","STRATEGO"],
  "Card games": ["BRIDGE","POKER","HEARTS","SPADES","RUMMY","CANASTA","EUCHRE","CRIBBAGE","PINOCHLE","GIN","SOLITAIRE"],
  "Card suits": ["HEARTS","DIAMONDS","CLUBS","SPADES"],
  "Casino games": ["ROULETTE","BLACKJACK","CRAPS","BACCARAT","SLOTS","POKER","KENO","FARO","PAI GOW"],
  "Classic video games": ["TETRIS","PONG","PACMAN","ASTEROIDS","GALAGA","CENTIPEDE","FROGGER","DONKEY KONG","SPACE INVADERS"],
  "Dance styles": ["TANGO","WALTZ","SWING","SALSA","FOXTROT","RUMBA","SAMBA","CHA CHA","PASO DOBLE","BOLERO","JIVE"],
  "Dances": ["TANGO","WALTZ","SWING","SALSA","FOXTROT","RUMBA","SAMBA","CHA CHA","PASO DOBLE","BOLERO","JIVE"],
  "Disney princesses": ["ARIEL","BELLE","MULAN","JASMINE","RAPUNZEL","MOANA","MERIDA","TIANA","POCAHONTAS","CINDERELLA"],
  "Dunder Mifflin employees": ["DWIGHT","ANGELA","KEVIN","OSCAR","STANLEY","PHYLLIS","MEREDITH","CREED","TOBY","KELLY"],
  "Fictional detectives": ["POIROT","MARPLE","COLUMBO","SHERLOCK","MORSE","CLOUSEAU","MONK","JESSICA FLETCHER","NANCY DREW"],
  "Fictional schools": ["HOGWARTS","XAVIER'S","BAYSIDE","SUNNYDALE","DEGRASSI","RYDELL","CHILTON","GREENDALE"],
  "Martial arts": ["KARATE","JUDO","TAEKWONDO","KUNG FU","AIKIDO","CAPOEIRA","KENDO","HAPKIDO","MUAY THAI","WING CHUN"],
  "Martial arts movies": ["ENTER THE DRAGON","CROUCHING TIGER","KILL BILL","KICKBOXER","BLOODSPORT","ONGBAK","IP MAN","FIST OF FURY"],
  "Monopoly spaces": ["BOARDWALK","PARK PLACE","MARVIN GARDENS","BALTIC","MEDITERRANEAN","READING","VENTNOR","ORIENTAL"],
  "Movie genres": ["HORROR","COMEDY","THRILLER","WESTERN","DRAMA","ACTION","ROMANCE","MYSTERY","FANTASY","SCI-FI","NOIR"],
  "Musical genres": ["JAZZ","BLUES","FUNK","SOUL","REGGAE","PUNK","GRUNGE","TECHNO","SWING","GOSPEL","DISCO","SKA"],
  "Types of music": ["JAZZ","BLUES","FUNK","SOUL","REGGAE","PUNK","GRUNGE","TECHNO","SWING","GOSPEL","DISCO"],
  "Olympic events": ["HURDLE","RELAY","VAULT","JAVELIN","DISCUS","SHOT PUT","MARATHON","DECATHLON","POLE VAULT","SPRINT"],
  "Olympic host cities": ["ATHENS","BEIJING","LONDON","TOKYO","PARIS","SYDNEY","BARCELONA","MUNICH","MOSCOW","ROME"],
  "Olympic medals": ["GOLD","SILVER","BRONZE"],
  "Olympic sports": ["FENCING","ARCHERY","ROWING","BOXING","JUDO","WRESTLING","DIVING","SAILING","EQUESTRIAN","KAYAK"],
  "Pixar films": ["TOY STORY","UP","COCO","WALL-E","BRAVE","RATATOUILLE","CARS","INSIDE OUT","SOUL","ONWARD","LUCA"],
  "Poker terms": ["BLUFF","RAISE","FOLD","ANTE","FLOP","RIVER","TURN","BLIND","ALL IN","CHECK","CALL"],
  "Seinfeld characters": ["KRAMER","GEORGE","ELAINE","NEWMAN","PUDDY","PETERMAN","BANIA","ESTELLE","FRANK"],
  "Shakespeare plays": ["HAMLET","OTHELLO","MACBETH","TEMPEST","TWELFTH NIGHT","LEAR","MIDSUMMER","CYMBELINE"],
  "Shakespearean characters": ["HAMLET","OTHELLO","MACBETH","OBERON","PUCK","PROSPERO","ARIEL","PORTIA","JULIET","OPHELIA"],
  "Star Wars characters": ["VADER","YODA","LEIA","HAN SOLO","CHEWBACCA","R2D2","BOBA FETT","PALPATINE","OBI-WAN","LUKE"],
  "Tarantino films": ["PULP FICTION","RESERVOIR DOGS","KILL BILL","DJANGO","HATEFUL EIGHT","JACKIE BROWN","INGLOURIOUS"],
  "Winter sports": ["SKIING","SKATING","HOCKEY","CURLING","LUGE","BOBSLED","BIATHLON","SKELETON","SNOWBOARD"],

  // MUSIC
  "90s bands that are also everyday words": ["GARBAGE","HOLE","BUSH","FUEL","CREED","LIVE","TOOL","CREAM","BREAD","STAIN"],
  "Artists who go by one name": ["PRINCE","SEAL","PINK","ADELE","BEYONCE","CHER","MADONNA","RIHANNA","DRAKE","USHER","JEWEL","BECK"],
  "Brass instruments": ["TRUMPET","TROMBONE","TUBA","FRENCH HORN","CORNET","BUGLE","EUPHONIUM","FLUGELHORN","SOUSAPHONE"],
  "Composers": ["BACH","MOZART","BEETHOVEN","CHOPIN","VIVALDI","BRAHMS","HANDEL","DEBUSSY","TCHAIKOVSKY","LISZT","WAGNER"],
  "Instruments": ["DRUM","FLUTE","HARP","CELLO","VIOLIN","GUITAR","OBOE","CLARINET","TRUMPET","TUBA","BASSOON","SITAR"],
  "Michael Jackson album titles": ["THRILLER","BAD","DANGEROUS","INVINCIBLE","HIStory","OFF THE WALL","BEN"],
  "Woodwind family": ["FLUTE","OBOE","CLARINET","BASSOON","PICCOLO","SAXOPHONE","ENGLISH HORN","RECORDER","FIFE"],
  "Woodwind instruments": ["FLUTE","OBOE","CLARINET","BASSOON","PICCOLO","SAXOPHONE","ENGLISH HORN","RECORDER","FIFE"],

  // CULTURE & LANGUAGE
  "Ancient civilizations": ["AZTEC","MAYA","INCA","SUMERIAN","BABYLONIAN","MINOAN","PHOENICIAN","ETRUSCAN","OLMEC"],
  "Ancient wonders": ["PYRAMIDS","COLOSSUS","LIGHTHOUSE","MAUSOLEUM","HANGING GARDENS","STATUE OF ZEUS","TEMPLE OF ARTEMIS"],
  "Famous addresses": ["DOWNING","BAKER","SESAME","ABBEY ROAD","BOURBON","BROADWAY","WALL","LOMBARD","SAVILE ROW"],
  "Famous Alexanders": ["HAMILTON","THE GREAT","GRAHAM BELL","POPE","MCQUEEN","PUSHKIN","CALDER","FLEMING"],
  "Famous Charleses": ["DARWIN","DICKENS","CHAPLIN","DE GAULLE","BARKLEY","BRONSON","MINGUS","SCHULZ"],
  "Famous Georges": ["WASHINGTON","CLOONEY","HARRISON","FOREMAN","LUCAS","ORWELL","STRAIT","BURNS"],
  "Famous Jacks": ["NICHOLSON","KENNEDY","BLACK","SPARROW","KEROUAC","LONDON","NICKLAUS","THE RIPPER"],
  "Famous Jameses": ["BOND","DEAN","BROWN","MADISON","JOYCE","BALDWIN","CAMERON","MONROE"],
  "Famous Johns": ["LENNON","KENNEDY","WAYNE","ADAMS","COLTRANE","ELTON","OLIVER","TRAVOLTA"],
  "Famous Michaels": ["JORDAN","JACKSON","PHELPS","SCHUMACHER","CAINE","DOUGLAS","KEATON","FARADAY"],
  "Famous Roberts": ["DE NIRO","REDFORD","DOWNEY","BURNS","FROST","PLANT","KENNEDY","MUGABE"],
  "Famous duos": ["BONNIE AND CLYDE","ROMEO AND JULIET","BATMAN AND ROBIN","SALT AND PEPPER","SIMON AND GARFUNKEL"],
  "Famous explorers": ["COLUMBUS","MAGELLAN","DRAKE","POLO","COOK","AMUNDSEN","CORTEZ","VESPUCCI","SHACKLETON"],
  "Famous last words": ["ROSEBUD","EUREKA","ALAS","BRAVO","CURTAIN","FAREWELL","ADIEU","FIN","CHECKMATE"],
  "Famous paintings": ["MONA LISA","STARRY NIGHT","GUERNICA","THE SCREAM","GIRL WITH A PEARL EARRING","NIGHTHAWKS"],
  "Famous robots": ["R2D2","HAL","WALL-E","OPTIMUS","DATA","BENDER","ROSIE","T-800","ROBOCOP","JOHNNY FIVE"],
  "Famous scientists": ["EINSTEIN","CURIE","DARWIN","NEWTON","TESLA","GALILEO","HAWKING","PASTEUR","FARADAY","BOHR"],
  "Greek gods": ["ZEUS","POSEIDON","HADES","ARES","APOLLO","HERMES","HEPHAESTUS","DIONYSUS","ATHENA","ARTEMIS"],
  "Greek letters": ["ALPHA","BETA","GAMMA","DELTA","EPSILON","SIGMA","OMEGA","PHI","PSI","TAU","THETA","LAMBDA","KAPPA"],
  "Latin phrases": ["CARPE DIEM","AD HOC","BONA FIDE","CAVEAT","ET CETERA","HABEAS CORPUS","IN VITRO","MAGNA CARTA","PERSONA","VICE VERSA","STATUS QUO"],
  "Mythical creatures": ["DRAGON","PHOENIX","GRIFFIN","UNICORN","MINOTAUR","CENTAUR","SPHINX","CHIMERA","HYDRA","CERBERUS","KRAKEN"],
  "Phonetic alphabet": ["ALPHA","BRAVO","CHARLIE","DELTA","ECHO","FOXTROT","GOLF","HOTEL","INDIA","JULIET","KILO","LIMA","MIKE","NOVEMBER","OSCAR","PAPA","QUEBEC","ROMEO","SIERRA","TANGO","UNIFORM","VICTOR","WHISKEY","XRAY","YANKEE","ZULU"],
  "Silent film stars": ["CHAPLIN","KEATON","LLOYD","VALENTINO","PICKFORD","FAIRBANKS","GISH","ARBUCKLE","NORMAND"],
  "Types of art": ["IMPRESSIONISM","CUBISM","SURREALISM","BAROQUE","RENAISSANCE","ABSTRACT","POP ART","REALISM","MINIMALISM"],
  "Types of government": ["DEMOCRACY","MONARCHY","OLIGARCHY","REPUBLIC","THEOCRACY","ANARCHY","AUTOCRACY","FEDERATION","COMMUNISM"],
  "Types of poetry": ["SONNET","HAIKU","LIMERICK","ODE","ELEGY","BALLAD","EPIC","FREE VERSE","VILLANELLE","SESTINA"],

  // THINGS WITH...
  "Colors of the rainbow": ["TEAL","MAGENTA","SCARLET","CRIMSON","AZURE","CORAL","MAROON","BURGUNDY","CERULEAN","CYAN"],
  "Shades of blue": ["NAVY","COBALT","CERULEAN","AZURE","TEAL","INDIGO","SAPPHIRE","TURQUOISE","ROYAL","POWDER","BABY","SKY"],
  "Words that are also colors": ["OLIVE","SILVER","IVORY","CORAL","AMBER","LAVENDER","MAUVE","CRIMSON","RUST","SAGE","BRONZE"],
  "Things with keys": ["ACCORDION","CASH REGISTER","ORGAN","TYPEWRITER","CALCULATOR","HARPSICHORD","SAFE","PADLOCK","DIARY"],
  "Things that glow": ["EMBER","FIREFLY","NEON","STAR","CANDLE","LANTERN","AURORA","PHOSPHORUS","GLOWWORM","LAVA","BEACON"],
  "Things that glow in the dark": ["FIREFLY","JELLYFISH","GLOW STICK","RADIUM","PHOSPHORUS","AURORA","GLOWWORM","ANGLERFISH"],
  "Things that spin": ["TOP","WHEEL","RECORD","TURBINE","PROPELLER","GYROSCOPE","DREIDEL","PINWHEEL","TORNADO","ROULETTE"],
  "Things with wings": ["AIRPLANE","ANGEL","BUTTERFLY","BAT","DRAGONFLY","EAGLE","BEE","MOTH","HAWK","PELICAN","STORK","HERON"],
  "Things that are red": ["CHERRY","FIRE ENGINE","CARDINAL","RUBY","SUNSET","BLOOD","ROSES","TOMATO","STRAWBERRY","LOBSTER"],
  "Things that rust": ["CHAIN","RAILING","PADLOCK","NAIL","ANCHOR","GATE","PIPE","FENCE","BRIDGE","BICYCLE","HINGE","GUTTER"],
  "Things that bounce": ["BALL","KANGAROO","SPRING","TRAMPOLINE","RUBBER DUCK","POGO STICK","BASKETBALL","SUPERBALL"],
  "Things that float": ["CORK","BOAT","DUCK","BUOY","LILY PAD","FEATHER","BALLOON","DRIFTWOOD","RAFT","ICE","LOG","CLOUD"],
  "Things that melt": ["ICE","SNOWMAN","CANDLE","BUTTER","CHOCOLATE","GLACIER","CHEESE","CRAYON","GELATO","WAX"],
  "Things that shimmer": ["SEQUIN","TINSEL","GLITTER","DEW","AURORA","PEARL","OPAL","FISH SCALE","MICA","SILK","MOONLIGHT"],
  "Things that sparkle": ["DIAMOND","GLITTER","CHAMPAGNE","FIREWORK","SEQUIN","CRYSTAL","STAR","TINSEL","FROST","MICA"],
  "Things that sizzle": ["BACON","STEAK","FAJITA","GRIDDLE","SKILLET","WOK","GRILL","TEMPURA","OIL","BUTTER"],
  "Things that crack": ["EGG","WHIP","ICE","KNUCKLE","GLASS","WALNUT","DAWN","CODE","SAFE","THUNDER","FIREPLACE"],
  "Things that drip": ["FAUCET","CANDLE","ICICLE","HONEY","PAINT","SWEAT","STALACTITE","RAIN","WAX","BLOOD"],
  "Things that echo": ["CANYON","CAVE","TUNNEL","CATHEDRAL","HALL","STAIRWELL","WELL","VALLEY","AMPHITHEATER"],
  "Things that pop": ["BALLOON","CORN","BUBBLE","CHAMPAGNE","CORK","FIRECRACKER","BLISTER","KNUCKLE","POPCORN"],
  "Things that buzz": ["BEE","FLY","MOSQUITO","ALARM","RAZOR","PHONE","NEON SIGN","TRANSFORMER","CICADA","HORNET"],
  "Things that hiss": ["SNAKE","STEAM","TIRE","CAT","RADIATOR","KETTLE","COBRA","PRESSURE COOKER","FUSE","VALVE"],
  "Things that roar": ["LION","THUNDER","ENGINE","WATERFALL","CROWD","BEAR","JET","TORNADO","FURNACE","DRAGON"],
  "Things that whistle": ["TRAIN","KETTLE","REFEREE","WIND","BIRD","TEAPOT","FLUTE","BULLET","MISSILE","LOBSTER POT"],
  "Things that howl": ["WOLF","WIND","DOG","COYOTE","BANSHEE","BLIZZARD","GALE","STORM","JACKAL","HYENA"],
  "Things that tick": ["CLOCK","WATCH","BOMB","METRONOME","TIMER","GEIGER COUNTER","HEART","BEETLE","CRICKET"],
  "Things that purr": ["CAT","ENGINE","MOTOR","KITTEN","VIBRATION","HELICOPTER","JAGUAR","PANTHER"],
  "Things that crawl": ["ANT","SPIDER","SNAKE","BABY","VINE","CATERPILLAR","CENTIPEDE","SLUG","CRAB","LIZARD","WORM"],
  "Things that sting": ["BEE","WASP","JELLYFISH","SCORPION","NETTLE","HORNET","FIRE ANT","STINGRAY","CORAL","THISTLE"],
  "Things that bloom": ["ROSE","TULIP","CHERRY TREE","ORCHID","DAISY","LILY","IRIS","MAGNOLIA","SUNFLOWER","PEONY"],
  "Things that bloom in spring": ["TULIP","DAFFODIL","CROCUS","CHERRY BLOSSOM","LILAC","IRIS","HYACINTH","BLUEBELL","MAGNOLIA"],
  "Things that sway": ["TREE","HAMMOCK","BRIDGE","PENDULUM","GRASS","CHANDELIER","LANTERN","WHEAT","PALM","REED"],
  "Things that cascade": ["WATERFALL","DOMINOES","FOUNTAIN","HAIR","FIREWORKS","CURTAIN","LAVA","SPARKS","CONFETTI"],
  "Things that crumble": ["COOKIE","CLIFF","FETA","SANDCASTLE","RUIN","PLASTER","BREAD","CHALK","EMPIRE","FOUNDATION"],
  "Things that fold": ["NAPKIN","CHAIR","MAP","PAPER","UMBRELLA","TOWEL","TENT","FAN","POKER HAND","ACCORDION"],
  "Things that unfold": ["PARACHUTE","NAPKIN","PAMPHLET","MAP","FLOWER","STORY","PLOT","BLANKET","FAN","ORIGAMI"],
  "Things that freeze": ["WATER","LAKE","PIPE","WINDSHIELD","POND","MEAT","SCREEN","COMPUTER","MOMENT","CREDIT CARD"],
  "Things that absorb": ["SPONGE","TOWEL","COTTON","SOIL","MOSS","PAPER","CLOTH","CHARCOAL","INSULATION","CARPET"],
  "Things that reflect": ["MIRROR","LAKE","GLASS","CHROME","FOIL","ICE","DIAMOND","PUDDLE","MOON","EYE","SHIELD"],
  "Things that bubble": ["CHAMPAGNE","HOT TUB","CAULDRON","SODA","SOAP","LAVA","SPRING","PANCAKE","CREEK"],
  "Things you blow": ["WHISTLE","CANDLE","NOSE","HORN","BUBBLE","TRUMPET","DANDELION","BALLOON","TROMBONE","CONCH"],
  "Round things": ["BALL","GLOBE","WHEEL","COIN","PIZZA","SUN","MOON","CLOCK","DONUT","ORANGE","MARBLE","RING","PEARL"],
  "Things with a blade": ["SCYTHE","SHEARS","CHISEL","SWORD","KNIFE","AXE","RAZOR","PLOW","FAN","TURBINE","SKATE","SAW"],
  "Things with a buckle": ["GAITER","HARNESS","STRAP","BELT","SHOE","HELMET","BACKPACK","WATCH","SANDAL","SUITCASE"],
  "Things with a knob": ["FAUCET","DIAL","DRAWER","DOOR","STOVE","RADIO","CANE","DRESSER","CABINET","VOLUME"],
  "Things with a sole": ["PUMP","SKATE","CLOG","BOOT","SANDAL","SNEAKER","SLIPPER","LOAFER","MOCCASIN","FLIP FLOP"],
  "Things with a handle": ["MUG","PAN","SUITCASE","DOOR","BROOM","UMBRELLA","BASKET","AXE","BUCKET","BRIEFCASE","SWORD"],
  "Things with a hook": ["CRANE","FISHING ROD","COAT RACK","PIRATE","ANCHOR","CROCHET","TOWING","BUNGEE","CURTAIN ROD"],
  "Things with a horn": ["UNICORN","RHINO","RAM","BULL","NARWHAL","ANTELOPE","MOOSE","CAR","BICYCLE","SAXOPHONE"],
  "Things with horns": ["UNICORN","RHINO","RAM","BULL","NARWHAL","ANTELOPE","MOOSE","BUFFALO","GOAT","VIKING"],
  "Things with a tail": ["KITE","FOX","COMET","PEACOCK","MERMAID","MONKEY","SCORPION","LIZARD","WHALE","DEVIL","RAT","DONKEY"],
  "Things with tails": ["KITE","FOX","COMET","PEACOCK","MERMAID","MONKEY","SCORPION","LIZARD","WHALE","DEVIL"],
  "Things with a face": ["CLOCK","COIN","CLIFF","MOUNTAIN","DICE","PLAYING CARD","WATCH","DOLL","BUILDING","CUBE"],
  "Things with a crown": ["KING","QUEEN","TOOTH","ROOSTER","PINEAPPLE","CHESS PIECE","ROLEX","STATUE","CRANE"],
  "Things with a ring": ["BELL","SATURN","BOXING","PHONE","TREE","CIRCUS","BINDER","ONION","OLYMPIC","ENGAGEMENT"],
  "Things with a shell": ["TURTLE","EGG","NUT","CLAM","SNAIL","LOBSTER","CRAB","TACO","OYSTER","MUSSEL","ARMADILLO"],
  "Things with scales": ["FISH","SNAKE","LIZARD","DRAGON","PANGOLIN","ARMADILLO","PIANO","BALANCE","MAP","JUSTICE"],
  "Things with strings": ["GUITAR","VIOLIN","PUPPET","KITE","HARP","BOW","BANJO","TENNIS RACKET","CELLO","YO-YO"],
  "Things with teeth": ["COMB","SAW","GEAR","ZIPPER","RAKE","SHARK","CROCODILE","KEY","CHAINSAW","PIRANHA"],
  "Things with feathers": ["PILLOW","ARROW","PEACOCK","EAGLE","PARROT","QUILL","SHUTTLECOCK","BOA","HEADDRESS","DUSTER"],
  "Things with bark": ["DOG","TREE","BIRCH","WILLOW","PINE","OAK","CORK","CINNAMON","REDWOOD","SEQUOIA"],
  "Things with layers": ["CAKE","ONION","LASAGNA","EARTH","PARFAIT","PAINT","SEDIMENT","PASTRY","TIRAMISU","BAKLAVA"],
  "Things with pedals": ["BICYCLE","PIANO","ORGAN","SEWING MACHINE","KAYAK","PEDAL BOAT","GO KART","HARPSICHORD"],
  "Things with pockets": ["JACKET","JEANS","BILLIARD TABLE","KANGAROO","VEST","BACKPACK","APRON","CARGO PANTS"],
  "Things with a stem": ["FLOWER","WINE GLASS","CHERRY","MUSHROOM","PIPE","WATCH","GOBLET","BROCCOLI","APPLE"],
  "Things with a spine": ["BOOK","CACTUS","HEDGEHOG","PORCUPINE","DINOSAUR","MOUNTAIN RANGE","URCHIN","STEGOSAURUS"],
  "Things with a spout": ["TEAPOT","KETTLE","WHALE","FOUNTAIN","WATERING CAN","GUTTER","PITCHER","JUG","GARGOYLE"],
  "Things with a vent": ["VOLCANO","DRYER","OVEN","CAR","BUILDING","SUBMARINE","SPACE SUIT","ATTIC","FURNACE"],
  "Things with a web": ["SPIDER","INTERNET","DUCK FOOT","FROG","SNOWSHOE","HAMMOCK","NET","LACE","DREAMCATCHER"],
  "Things with a wheel": ["BICYCLE","CAR","WAGON","SHIP","ROULETTE","HAMSTER","TRICYCLE","SKATEBOARD","POTTERY","MILL"],
  "Things with a wing": ["AIRPLANE","BIRD","BAT","BUTTERFLY","BUILDING","HOSPITAL","STAGE","ANGEL","MOTH","MANSION"],
  "Things with a net": ["TENNIS","BASKETBALL","FISHING","VOLLEYBALL","BADMINTON","SOCCER","TRAMPOLINE","HAMMOCK","CIRCUS"],
  "Things with a paddle": ["CANOE","KAYAK","PING PONG","ROWBOAT","MIXER","BUTTER CHURN","DUCKLING","PICKLEBALL"],
  "Things with a point": ["PENCIL","ARROW","COMPASS","STAR","NEEDLE","SWORD","PYRAMID","MOUNTAIN","ANTLER","SPEAR"],
  "Things with a plug": ["BATHTUB","LAMP","CHARGER","SINK","GUITAR","SPARK","EARPHONE","POWER STRIP","APPLIANCE"],
  "Things with a lid": ["JAR","POT","COFFIN","DUMPSTER","TRASH CAN","TEAPOT","BOX","CHEST","TUPPERWARE","EYE"],
  "Things with a loop": ["BELT","ROLLER COASTER","LASSO","THREAD","SHOELACE","EARRING","KNOT","HOOP","KEYCHAIN"],
  "Things with a lens": ["CAMERA","TELESCOPE","MICROSCOPE","BINOCULARS","GLASSES","PROJECTOR","EYE","MAGNIFIER","LIGHTHOUSE"],
  "Things with a frame": ["PICTURE","BICYCLE","DOOR","WINDOW","BED","MIRROR","GLASSES","TENT","BUILDING","LOOM"],
  "Things with a fuse": ["BOMB","FIRECRACKER","CIRCUIT BREAKER","DYNAMITE","ROCKET","APPLIANCE","ELECTRICAL BOX"],
  "Things with a gauge": ["FUEL","PRESSURE","RAIN","SPEEDOMETER","THERMOMETER","BAROMETER","TIRE","RAILROAD","SHOTGUN"],
  "Things with a grid": ["CROSSWORD","CHESS BOARD","WAFFLE","WINDOW","SPREADSHEET","CALENDAR","CITY","MAP","GRAPH"],
  "Things with a cork": ["WINE BOTTLE","BULLETIN BOARD","FISHING ROD","CHAMPAGNE","THERMOS","FLASK","BAT"],
  "Things with a cord": ["PHONE","BLINDS","PARACHUTE","LAMP","BUNGEE","HEADPHONE","EXTENSION","GUITAR","ROBE"],
  "Things with a cap": ["BOTTLE","MUSHROOM","PEN","KNEE","TOOTH","GRADUATION","NURSE","SNOW","BASEBALL"],
  "Things with a bed": ["RIVER","TRUCK","FLOWER","NAIL","HOTEL","HOSPITAL","OYSTER","LAKE","GARDEN","TEST"],
  "Things with a bank": ["RIVER","MONEY","SNOW","BLOOD","MEMORY","FOG","SAND","PIGGY","POOL","DATA"],
  "Things with a bark": ["DOG","TREE","WILLOW","OAK","CINNAMON","BIRCH","PINE","REDWOOD","SEQUOIA","ELM"],
  "Things with a beak": ["BIRD","PLATYPUS","OCTOPUS","SQUID","TURTLE","PENGUIN","PARROT","TOUCAN","PUFFIN","FINCH"],
  "Things with a beam": ["FLASHLIGHT","BARN","LIGHTHOUSE","LASER","SUNLIGHT","GYMNAST","BRIDGE","CEILING","STAGE"],
  "Things with a bell": ["CHURCH","CAT","BICYCLE","DOORBELL","SCHOOL","SLEIGH","JESTER","COW","TELEPHONE","ALARM"],
  "Things with a bridge": ["GUITAR","NOSE","RIVER","SHIP","VIOLIN","DENTURE","GAME","CARD","GLASSES","SONG"],
  "Things with a brim": ["HAT","CUP","BOWL","VOLCANO","CAULDRON","SOMBRERO","TOP HAT","FEDORA","STETSON"],
  "Things with a chamber": ["HEART","GUN","CAVE","SENATE","ECHO","MUSIC","NAUTILUS","CASTLE","TOMB","MINE"],
  "Things with a channel": ["RIVER","TELEVISION","ENGLISH","PANAMA","RADIO","IRRIGATION","TUNNEL","COMMUNICATION"],
  "Things with a clasp": ["NECKLACE","BRACELET","PURSE","ENVELOPE","BINDER","BROOCH","LOCKET","BRIEFCASE"],
  "Things with a dial": ["CLOCK","PHONE","RADIO","SAFE","COMPASS","OVEN","THERMOSTAT","SPEEDOMETER","WATCH","METER"],
  "Things with a dock": ["BOAT","PHONE","LAPTOP","HARBOR","LOADING","SPACE STATION","COURTROOM","PIER"],
  "Things with a drum": ["WASHING MACHINE","BAND","ORCHESTRA","COFFEE ROASTER","CABLE","SCANNER","PRINTER"],
  "Things with a fin": ["SHARK","DOLPHIN","WHALE","SURFBOARD","ROCKET","AIRPLANE","FISH","SUBMARINE","CAR","RADIATOR"],
  "Things with a harbor": ["CITY","ISLAND","COAST","PORT","NAVY","YACHT","PEARL","MARINA","LIGHTHOUSE","BREAKWATER"],
  "Things with a hatch": ["SHIP","SUBMARINE","EGG","TRAPDOOR","SPACECRAFT","ATTIC","CELLAR","TURTLE","CHICKEN"],
  "Things with a hinge": ["DOOR","LID","GATE","LAPTOP","SHELL","JAW","CLAM","OYSTER","TRUNK","TOOLBOX"],
  "Things with a magnet": ["FRIDGE","COMPASS","SPEAKER","HARD DRIVE","CRANE","MRI MACHINE","MOTOR","GENERATOR"],
  "Things with a mane": ["LION","HORSE","ZEBRA","GIRAFFE","WILDEBEEST","HYENA","UNICORN","PONY","BISON","YAK"],
  "Things with a mirror": ["BATHROOM","TELESCOPE","LASER","FUNHOUSE","VANITY","CAR","DISCO BALL","KALEIDOSCOPE"],
  "Things with a motor": ["CAR","BOAT","FAN","BLENDER","DRILL","ELEVATOR","ESCALATOR","REFRIGERATOR","LAWN MOWER"],
  "Things with a mouth": ["RIVER","CAVE","VOLCANO","BOTTLE","JAR","PUPPET","TUNNEL","HARBOR","CANNON","WELL"],
  "Things with a nest": ["BIRD","BEE","WASP","ANT","EAGLE","SQUIRREL","MOUSE","RABBIT","TURTLE","HORNET"],
  "Things with a patch": ["PIRATE","JACKET","TIRE","GARDEN","EYE","QUILT","SOFTWARE","PUMPKIN","FIELD","CABBAGE"],
  "Things with a peak": ["MOUNTAIN","CAP","ROOF","WAVE","CAREER","PERFORMANCE","GRAPH","DAWN","INTEREST","FEVER"],
  "Things with a pedestal": ["STATUE","TROPHY","VASE","SINK","COLUMN","BIRDBATH","LAMP","BUST","GLOBE","SCULPTURE"],
  "Things with a perch": ["BIRD","FISH","PARROT","FALCON","OWL","ROOSTER","GARGOYLE","LOOKOUT","BALCONY","LEDGE"],
  "Things with a pit": ["CHERRY","PEACH","AVOCADO","OLIVE","PLUM","ORCHESTRA","BARBECUE","MINE","SNAKE","TRACK"],
  "Things with a plume": ["PEACOCK","HELMET","VOLCANO","OSTRICH","SMOKE","FOUNTAIN","PEN","ROOSTER","HEADDRESS"],
  "Things with a pocket": ["JACKET","JEANS","POOL TABLE","KANGAROO","VEST","BACKPACK","APRON","CARGO PANTS","SHIRT"],
  "Things with a propeller": ["AIRPLANE","HELICOPTER","BOAT","FAN","DRONE","SUBMARINE","BEANIE","WIND TURBINE"],
  "Things with a root": ["TREE","TOOTH","HAIR","WORD","CARROT","GINGER","BEET","PROBLEM","EQUATION","FAMILY"],
  "Things with a rudder": ["SHIP","AIRPLANE","SAILBOAT","KAYAK","SUBMARINE","CANOE","BLIMP","SURFBOARD"],
  "Things with a saddle": ["HORSE","BICYCLE","MOTORCYCLE","MOUNTAIN","GUITAR","CAMEL","DONKEY","TRACTOR","SHOE"],
  "Things with a scale": ["FISH","SNAKE","MAP","PIANO","JUSTICE","BATHROOM","DRAGON","GUITAR","MUSIC","KITCHEN"],
  "Things with a stage": ["THEATER","ROCKET","CONCERT","MICROSCOPE","GRIEF","DISEASE","GAME","LIFE","TOUR","PLAY"],
  "Things with a strap": ["WATCH","GUITAR","BACKPACK","SANDAL","HELMET","PURSE","CAMERA","MASK","SEATBELT","GOGGLES"],
  "Things with a stripe": ["ZEBRA","TIGER","FLAG","CANDY CANE","SKUNK","BARBER POLE","REFEREE","BEE","BUMBLE BEE","CORAL SNAKE"],
  "Things with a tongue": ["SHOE","BELT BUCKLE","FLAME","SNAKE","BELL","ENVELOPE","CHAMELEON","WAGON","DOG","FROG"],
  "Things with a track": ["TRAIN","TANK","MUSIC","RACE","HORSE","BULLDOZER","RECORD","CURTAIN","SATELLITE","CATERPILLAR"],
  "Things with a trunk": ["ELEPHANT","CAR","TREE","SUITCASE","CHEST","BODY","SWIMMER","TELEPHONE","STEAMER"],
  "Things have a trunk": ["ELEPHANT","CAR","TREE","SUITCASE","CHEST","BODY","SWIMMER","TELEPHONE","STEAMER"],
  "Things with a valve": ["TRUMPET","HEART","TIRE","PIPE","RADIATOR","ENGINE","SCUBA TANK","TROMBONE","FAUCET"],
  "Things with an antenna": ["RADIO","TV","INSECT","SATELLITE","CAR","SNAIL","LOBSTER","CRAYFISH","BUTTERFLY","ROUTER"],
  "Things with handles": ["MUG","PAN","SUITCASE","DOOR","BROOM","UMBRELLA","BASKET","AXE","BUCKET","BRIEFCASE"],
  "Things with a zipper": ["JACKET","TENT","SLEEPING BAG","SUITCASE","BACKPACK","JEANS","DRESS","BOOT","PURSE","PENCIL CASE"],

  // THINGS THAT...
  "Things that are braided": ["BREAD","ROPE","HAIR","RUG","BELT","PRETZEL","LANYARD","CHALLAH","LEATHER","GARLIC"],
  "Things that are coiled": ["SPRING","SNAKE","ROPE","HOSE","CORD","FERN","DNA","WIRE","GARDEN HOSE","LASSO"],
  "Things that are crispy": ["BACON","TOAST","CHIP","CRACKER","FRIED CHICKEN","TEMPURA","SPRING ROLL","WAFER","PRETZEL","CROUTON"],
  "Things that are elastic": ["RUBBER BAND","WAISTBAND","TRAMPOLINE","BUNGEE","SPANDEX","SLINGSHOT","SKIN","MUSCLE"],
  "Things that are frozen": ["ICE","GLACIER","TUNDRA","POPSICLE","GELATO","MEAT","WATERFALL","LAKE","POND","MARGARITA"],
  "Things that are hollow": ["TUBE","PIPE","BONE","TREE","CHOCOLATE","LOG","BAMBOO","REED","DRUM","GOURD"],
  "Things that are inflatable": ["BALLOON","RAFT","POOL","MATTRESS","CASTLE","TIRE","LIFE VEST","AIRBAG","BEACH BALL"],
  "Things that are layered": ["CAKE","ONION","LASAGNA","EARTH","PARFAIT","PAINT","SEDIMENT","PASTRY","TIRAMISU"],
  "Things that are round": ["BALL","GLOBE","WHEEL","COIN","PIZZA","SUN","MOON","CLOCK","DONUT","ORANGE"],
  "Things that are sharp": ["KNIFE","NEEDLE","THORN","CLAW","RAZOR","PENCIL","CHEDDAR","WIT","TONGUE","TOOTH"],
  "Things that are sticky": ["TAPE","HONEY","GLUE","SAP","GUM","MOLASSES","JAM","TOFFEE","SPIDER WEB","RESIN"],
  "Things that are tangled": ["HEADPHONES","CHRISTMAS LIGHTS","FISHING LINE","HAIR","YARN","SPAGHETTI","ROPE","WIRE","VINES"],
  "Things that are transparent": ["GLASS","WATER","ICE","CRYSTAL","CELLOPHANE","WINDOW","JELLYFISH","DIAMOND","FILM"],
  "Things that are winding": ["ROAD","RIVER","STAIRCASE","PATH","CREEK","TRAIL","CLOCK","CANYON","THREAD","VINE"],
  "Things that are woven": ["BASKET","FABRIC","RUG","TAPESTRY","MAT","BLANKET","HAMMOCK","SCARF","NET","FENCE"],
  "Things that crack under pressure": ["ICE","GLASS","EGG","DAM","NUT","FOUNDATION","SUSPECT","VOICE","BRIDGE","WINDOW"],
  "Things that launch": ["ROCKET","MISSILE","BOAT","CAMPAIGN","PRODUCT","TORPEDO","FIREWORK","SATELLITE","CAREER","APP"],
  "Things that orbit": ["MOON","SATELLITE","PLANET","COMET","ASTEROID","ELECTRON","SPACE STATION","SPACECRAFT"],
  "Things that tower": ["SKYSCRAPER","LIGHTHOUSE","CASTLE","REDWOOD","SEQUOIA","GIRAFFE","CRANE","CATHEDRAL","SILO"],

  // THINGS AT...
  "Things at a bar": ["STOOL","TAP","COASTER","SHAKER","JIGGER","GARNISH","MUDDLER","SHOT GLASS","NAPKIN","ICE BUCKET"],
  "Things at a campsite": ["TENT","FIRE PIT","SLEEPING BAG","COOLER","LANTERN","FIREWOOD","MARSHMALLOW","COMPASS","AXE","CANTEEN"],
  "Things at a carnival": ["FERRIS WHEEL","COTTON CANDY","FUNNEL CAKE","CAROUSEL","BUMPER CAR","CLOWN","BALLOON","POPCORN"],
  "Things at a circus": ["TRAPEZE","ACROBAT","RINGMASTER","TIGHTROPE","JUGGLER","LION","CANNON","TENT","CLOWN"],
  "Things at a concert": ["STAGE","SPEAKER","TICKET","ENCORE","SETLIST","ROADIE","MOSH PIT","SPOTLIGHT","AMPLIFIER"],
  "Things at a desk": ["STAPLER","LAMP","PEN","MOUSE","MONITOR","KEYBOARD","NOTEBOOK","PAPERWEIGHT","CALENDAR","CUP"],
  "Things at a farm": ["BARN","TRACTOR","SILO","SCARECROW","HAYSTACK","FENCE","WINDMILL","PLOW","ROOSTER","PASTURE"],
  "Things at a picnic": ["BLANKET","BASKET","COOLER","LEMONADE","SANDWICH","ANTS","NAPKIN","FRISBEE","THERMOS","SALAD"],
  "Things at a spa": ["SAUNA","ROBE","CUCUMBER","TOWEL","CANDLE","MUD BATH","MASSAGE","HOT TUB","LOTION","FACIAL"],
  "Things at a wedding": ["BOUQUET","VEIL","CAKE","TOAST","RING","VOWS","GARTER","USHER","AISLE","RECEPTION","BAND"],
  "Things at an airport": ["TERMINAL","GATE","RUNWAY","BAGGAGE","CUSTOMS","CONTROL TOWER","HANGAR","TARMAC","LOUNGE"],
  "Things at the beach": ["SANDCASTLE","UMBRELLA","SURFBOARD","SEASHELL","SUNSCREEN","TOWEL","LIFEGUARD","DUNE","WAVE"],
  "Things in a classroom": ["CHALK","DESK","GLOBE","ERASER","PENCIL","TEXTBOOK","WHITEBOARD","BACKPACK","RULER","BELL"],
  "Things in a cockpit": ["JOYSTICK","ALTIMETER","THROTTLE","RADAR","COMPASS","HEADSET","GAUGE","SWITCH","RUDDER PEDAL"],
  "Things in a courtroom": ["GAVEL","JURY","WITNESS","BAILIFF","BENCH","OATH","VERDICT","DOCKET","JUDGE","STENOGRAPHER"],
  "Things in a gym": ["DUMBBELL","TREADMILL","BENCH PRESS","MAT","BARBELL","KETTLEBELL","PULL-UP BAR","ROPE","SQUAT RACK"],
  "Things in a gym locker": ["TOWEL","LOCK","DEODORANT","SHAMPOO","SNEAKERS","WATER BOTTLE","SWEATBAND","SOCKS"],
  "Things in a park": ["BENCH","FOUNTAIN","SWING","SLIDE","TREE","POND","PATH","GAZEBO","KITE","PICNIC TABLE"],
  "Things in a pocket": ["KEYS","WALLET","PHONE","COIN","LINT","TISSUE","GUM","RECEIPT","LIGHTER","PEN","CHAPSTICK"],
  "Things in a purse": ["WALLET","KEYS","LIPSTICK","MIRROR","GUM","TISSUE","PHONE","PEN","MINTS","HAND CREAM"],
  "Things in a studio": ["EASEL","CANVAS","PALETTE","BRUSH","MICROPHONE","SPEAKER","CAMERA","TRIPOD","SPOTLIGHT","MIXER"],
  "Things in a toolbox": ["HAMMER","WRENCH","SCREWDRIVER","PLIERS","TAPE MEASURE","LEVEL","DRILL","SOCKET","CHISEL","SAW"],
  "Things in a wallet": ["CASH","CARD","LICENSE","PHOTO","RECEIPT","STAMP","TICKET","COUPON","COIN","ID"],
  "Things in an office": ["STAPLER","PRINTER","DESK","CHAIR","PHONE","CALENDAR","BINDER","SHREDDER","CLIPBOARD","WHITEBOARD"],

  // EQUIPMENT & TOOLS
  "Camping gear": ["TENT","SLEEPING BAG","COMPASS","FLASHLIGHT","CANTEEN","BINOCULARS","TARP","STOVE","FIRST AID KIT","HATCHET"],
  "Climbing gear": ["HARNESS","CARABINER","CHALK BAG","ROPE","CRAMPON","PITON","BELAY DEVICE","ICE AXE","HELMET","ASCENDER"],
  "Climbing plants": ["IVY","WISTERIA","CLEMATIS","JASMINE","HONEYSUCKLE","BOUGAINVILLEA","MORNING GLORY","GRAPE VINE","HOP","PASSIONFLOWER"],
  "Diving equipment": ["MASK","SNORKEL","FINS","WETSUIT","TANK","REGULATOR","BCD","WEIGHT BELT","DIVE COMPUTER"],
  "Gym equipment": ["BENCH","PULLUP BAR","MEDICINE BALL","TREADMILL","DUMBBELL","KETTLEBELL","BARBELL","SQUAT RACK","ROWING MACHINE"],
  "Kitchen appliances": ["TOASTER","BLENDER","MIXER","MICROWAVE","OVEN","DISHWASHER","FOOD PROCESSOR","JUICER","WAFFLE IRON"],
  "Kitchen tools": ["WHISK","LADLE","TONGS","GRATER","SPATULA","PEELER","COLANDER","SIEVE","ROLLING PIN","MORTAR"],
  "Tools": ["HAMMER","WRENCH","SCREWDRIVER","PLIERS","SAW","DRILL","CHISEL","LEVEL","CLAMP","VISE","RASP","FILE"],

  // CLOTHING
  "Fabrics": ["SILK","DENIM","COTTON","VELVET","LINEN","SATIN","WOOL","CASHMERE","CHIFFON","TWEED","FLANNEL","CORDUROY","ORGANZA"],
  "Pelts and furs": ["MINK","SABLE","FOX","BEAVER","CHINCHILLA","ERMINE","OTTER","RABBIT","RACCOON","SEAL"],
  "Shoes": ["LOAFER","SANDAL","MULE","PUMP","SNEAKER","BOOT","CLOG","OXFORD","STILETTO","ESPADRILLE","DERBY","BROGUE"],
  "Types of hat": ["FEDORA","BERET","BOWLER","STETSON","DERBY","CLOCHE","TURBAN","TRILBY","FEZ","SOMBRERO","PITH"],
  "Types of hats": ["FEDORA","BERET","BOWLER","STETSON","DERBY","CLOCHE","TURBAN","TRILBY","FEZ","SOMBRERO"],
  "Winter clothing": ["SCARF","MITTEN","PARKA","EARMUFF","THERMAL","BEANIE","GLOVE","OVERCOAT","FLEECE","SNOWSUIT"],

  // TRANSPORTATION
  "Currencies": ["POUND","FRANC","CROWN","BUCK","YEN","EURO","PESO","RUPEE","DINAR","RAND","KRONE","LIRA","SHEKEL"],
  "Currencies of the world": ["POUND","FRANC","CROWN","YEN","EURO","PESO","RUPEE","DINAR","RAND","KRONE","LIRA"],
  "Modes of transport": ["FERRY","CABLE CAR","RICKSHAW","GONDOLA","TROLLEY","MONORAIL","HOVERCRAFT","CANOE","BLIMP"],
  "Parts of a ship": ["HULL","BOW","STERN","MAST","KEEL","RUDDER","ANCHOR","DECK","GALLEY","PORTHOLE","HELM","RIGGING"],
  "Trees": ["MAPLE","WILLOW","CEDAR","BIRCH","OAK","PINE","ELM","ASH","SPRUCE","FIR","CYPRESS","HEMLOCK","REDWOOD","BEECH","POPLAR","ALDER"],
  "Flowers": ["ZINNIA","ASTER","MARIGOLD","ROSE","TULIP","DAISY","LILY","ORCHID","IRIS","PEONY","POPPY","DAHLIA","SUNFLOWER","CARNATION","JASMINE","VIOLET","LOTUS","DAFFODIL","LAVENDER","CHRYSANTHEMUM","HYACINTH","HIBISCUS","AZALEA","BEGONIA","CAMELLIA"],
  "Garden flowers": ["ROSE","TULIP","DAISY","LILY","ORCHID","IRIS","PEONY","SUNFLOWER","CARNATION","SNAPDRAGON","GERANIUM"],
  "Knots": ["BOWLINE","CLOVE HITCH","FIGURE EIGHT","REEF","SQUARE","SLIP","TIMBER HITCH","SHEET BEND","OVERHAND"],
  "Types of knot": ["BOWLINE","CLOVE HITCH","FIGURE EIGHT","REEF","SQUARE","SLIP","TIMBER HITCH","SHEET BEND"],
  "Types of bridge": ["ARCH","SUSPENSION","CANTILEVER","TRUSS","BEAM","CABLE-STAYED","DRAWBRIDGE","PONTOON","COVERED"],
  "Scrabble high-point letters": ["Q","Z","X","J","K"],
  "Silent letters (has one)": ["KNIGHT","PSALM","GNAT","WRITE","DOUBT","ISLAND","SUBTLE","DEBRIS","HONOR","RECEIPT","PNEUMONIA"],

  // WORD GAMES
  "Palindromes": ["LEVEL","MADAM","RACECAR","KAYAK","CIVIC","ROTOR","DEIFIED","RADAR","REFER","TENET","NOON","DEED","STATS"],
  "Portmanteau words": ["BRUNCH","SMOG","MOTEL","PODCAST","BLOG","SITCOM","INFOMERCIAL","GLAMPING","FRENEMY","JEGGINGS"],
  "Compound words with SUN": ["SUNFLOWER","SUNRISE","SUNSET","SUNBURN","SUNDIAL","SUNLIGHT","SUNSCREEN","SUNBEAM","SUNSPOT"],
  "Words ending in -ight": ["LIGHT","NIGHT","FLIGHT","SIGHT","HEIGHT","PLIGHT","BLIGHT","KNIGHT","FRIGHT","MIGHT","BRIGHT","TIGHT","SLIGHT","DELIGHT"],
  "Words ending in -ous": ["FAMOUS","NERVOUS","CURIOUS","FURIOUS","JEALOUS","PREVIOUS","OBVIOUS","SERIOUS","PRECIOUS","GORGEOUS"],
  "Words ending in -tion": ["NATION","STATION","MOTION","POTION","FICTION","ACTION","CAUTION","MENTION","PORTION","FASHION"],
  "Words from Arabic": ["ALGEBRA","COTTON","LEMON","MAGAZINE","SAFARI","ZERO","CIPHER","TARIFF","CARAVAN","MONSOON"],
  "Words from Dutch": ["COOKIE","COLESLAW","YACHT","EASEL","BOSS","FREIGHT","KNAPSACK","LANDSCAPE","WAGON","DOPE"],
  "Words from French": ["BALLET","CUISINE","FACADE","CHAUFFEUR","BOUTIQUE","PLATEAU","DEBRIS","ROUGE","SOUVENIR","SILHOUETTE"],
  "Words from Hindi": ["JUNGLE","BUNGALOW","SHAMPOO","PAJAMAS","LOOT","THUG","VERANDA","AVATAR","GURU","NIRVANA"],
  "Words from Italian": ["PIANO","SOPRANO","FIASCO","VOLCANO","MANIFESTO","GRAFFITI","MAESTRO","INFERNO","STUCCO","GHETTO"],
  "Words from Japanese": ["KARATE","TSUNAMI","EMOJI","ORIGAMI","TYPHOON","TOFU","SAKE","FUTON","RAMEN","WASABI"],
  "Words from Portuguese": ["ALBINO","CASHEW","COCONUT","MARMALADE","PAGODA","PALAVER","TANK","ZEBRA","FLAMINGO","DODO"],
  "Words from Spanish": ["TORNADO","CARGO","PLAZA","VANILLA","BREEZE","MOSQUITO","CANOE","RANCH","RODEO","PATIO"],
  "Words that are also dances": ["WALTZ","TWIST","SWING","JIVE","STOMP","HUSTLE","SHIMMY","HOP","SKIP","SLIDE","SHUFFLE"],
  "Words that are also months": ["MARCH","MAY","AUGUST","JUNE","APRIL"],
  "Words that contain a body part": ["HEARTH","ELBOW","KNEECAP","THUMBNAIL","HANDSOME","EYEBROW","SHOULDER","FOOTPRINT","ARMADILLO"],
  "Words that sound like numbers": ["WON","ATE","FORE","TOO","SEW","KNIGHT","SICKS","WANE","FEE","TREE"],
  "Words with QU": ["QUILT","QUEEN","QUEST","QUIZ","QUOTA","QUIVER","QUARRY","QUORUM","QUINTET","QUANTUM"],
  "Words with all vowels": ["SEQUOIA","FACETIOUS","ABSTEMIOUS","EDUCATION","EVACUATION","EQUATION","BEHAVIOUR"],
  "Words with double O": ["BAMBOO","VOODOO","TABOO","HOODOO","IGLOO","SHAMPOO","TATTOO","KANGAROO","COCKATOO","MONSOON"],
  "Words with silent B": ["DOUBT","PLUMBER","SUBTLE","CLIMB","TOMB","COMB","LAMB","CRUMB","THUMB","NUMB","LIMB","BOMB","DEBT"],

  // SYNONYMS - MEANINGS
  "Words meaning 'a lot'": ["PLETHORA","MYRIAD","OODLES","ABUNDANCE","SLEW","PROFUSION","MULTITUDE","SURFEIT"],
  "Words meaning 'angry'": ["IRATE","FURIOUS","LIVID","INCENSED","WRATHFUL","SEETHING","ENRAGED","INDIGNANT"],
  "Words that mean 'angry'": ["IRATE","FURIOUS","LIVID","INCENSED","WRATHFUL","SEETHING","ENRAGED","INDIGNANT"],
  "Words meaning 'beautiful'": ["GORGEOUS","STUNNING","RADIANT","EXQUISITE","SUBLIME","RESPLENDENT","DAZZLING","COMELY"],
  "Words meaning 'big'": ["MASSIVE","COLOSSAL","ENORMOUS","IMMENSE","GIGANTIC","VAST","MAMMOTH","TITANIC","GARGANTUAN"],
  "Words meaning 'brave'": ["VALIANT","GALLANT","COURAGEOUS","INTREPID","DAUNTLESS","FEARLESS","BOLD","STALWART","RESOLUTE"],
  "Words meaning 'bright'": ["BRILLIANT","RADIANT","LUMINOUS","VIVID","DAZZLING","GLEAMING","RESPLENDENT","LUSTROUS","INCANDESCENT"],
  "Words meaning 'calm'": ["SERENE","PLACID","TRANQUIL","COMPOSED","UNRUFFLED","EQUANIMOUS","HALCYON","PACIFIC","MELLOW"],
  "Words meaning 'clever'": ["ASTUTE","SHREWD","SAVVY","CUNNING","INGENIOUS","ADROIT","CANNY","WILY","CRAFTY"],
  "Words meaning 'crazy'": ["BONKERS","LOOPY","NUTTY","BATTY","ZANY","WACKY","BARMY","DOTTY","KOOKY","MADCAP"],
  "Words meaning 'edge'": ["BRINK","VERGE","FRINGE","MARGIN","PERIPHERY","RIM","BORDER","BRIM","THRESHOLD","CUSP"],
  "Words meaning 'empty'": ["VACANT","VOID","BARREN","HOLLOW","DESOLATE","BLANK","BARE","BEREFT","DESERTED","FORSAKEN"],
  "Words meaning 'fake'": ["BOGUS","SHAM","PHONY","SPURIOUS","ERSATZ","PSEUDO","COUNTERFEIT","MOCK","FAUX","FORGED"],
  "Words meaning 'fast'": ["SWIFT","RAPID","BRISK","FLEET","HASTY","SPEEDY","NIMBLE","ZIPPY","BLISTERING","BREAKNECK"],
  "Words meaning 'foolish'": ["DAFT","INANE","ASININE","ABSURD","FATUOUS","VAPID","WITLESS","LUDICROUS","PREPOSTEROUS"],
  "Words meaning 'group'": ["CLUSTER","TROOP","COHORT","CADRE","BATTALION","ENSEMBLE","FLOCK","HERD","PACK","GAGGLE","SWARM"],
  "Words meaning 'happy'": ["ELATED","JUBILANT","ECSTATIC","BLISSFUL","GLEEFUL","EUPHORIC","BUOYANT","JOVIAL","MIRTHFUL","RADIANT"],
  "Words meaning 'lazy'": ["INDOLENT","SLOTHFUL","LANGUID","LETHARGIC","SLUGGISH","LISTLESS","TORPID","IDLE","INERT"],
  "Words meaning 'leave'": ["DEPART","VACATE","ABSCOND","FLEE","WITHDRAW","EXIT","RETREAT","ABANDON","EVACUATE","BOLT"],
  "Words meaning 'loud'": ["RAUCOUS","BOOMING","THUNDEROUS","BLARING","DEAFENING","CLAMOROUS","STENTORIAN","PIERCING","SHRILL"],
  "Words meaning 'money'": ["DOUGH","BREAD","MOOLAH","BUCKS","LOOT","CASH","LUCRE","CHEDDAR","GREENBACK","QUID"],
  "Words meaning 'mysterious'": ["ENIGMATIC","CRYPTIC","ARCANE","ESOTERIC","INSCRUTABLE","OCCULT","ELUSIVE","ABSTRUSE","OPAQUE"],
  "Words meaning 'new'": ["NOVEL","FRESH","NASCENT","BUDDING","FLEDGLING","PRISTINE","INFANT","EMERGENT","MAIDEN","VIRGIN"],
  "Words meaning 'nonsense'": ["DRIVEL","HOGWASH","BALDERDASH","BUNKUM","TWADDLE","CLAPTRAP","GOBBLEDYGOOK","POPPYCOCK","TRIPE","PIFFLE"],
  "Words meaning 'old'": ["ANCIENT","ARCHAIC","ANTIQUE","VENERABLE","VINTAGE","AGED","HOARY","DECREPIT","FOSSIL"],
  "Words meaning 'pale'": ["ASHEN","PALLID","GHOSTLY","SALLOW","BLANCHED","WAN","PASTY","ANEMIC","FADED","WAXEN"],
  "Words meaning 'rare'": ["SCARCE","SPARSE","UNCOMMON","EXOTIC","SINGULAR","UNIQUE","EXCEPTIONAL","ELUSIVE","INFREQUENT"],
  "Words meaning 'run'": ["SPRINT","DASH","BOLT","GALLOP","SCAMPER","SCURRY","JOG","LOPE","TROT","CANTER"],
  "Words meaning 'scared'": ["PETRIFIED","TERRIFIED","AGHAST","PANICKED","HORRIFIED","ALARMED","DAUNTED","SPOOKED","RATTLED","SHAKEN"],
  "Words meaning 'small'": ["TINY","PETITE","MINUSCULE","DIMINUTIVE","MINIATURE","WEE","PUNY","PINT-SIZED","COMPACT","MEAGER"],
  "Words meaning 'smart'": ["ASTUTE","SHREWD","SAVVY","SHARP","KEEN","BRILLIANT","PERCEPTIVE","BRAINY","QUICK-WITTED","ADEPT"],
  "Words meaning 'steal'": ["PILFER","SWIPE","FILCH","PURLOIN","PLUNDER","PINCH","POCKET","SNATCH","EMBEZZLE","LOOT"],
  "Words meaning 'strong'": ["ROBUST","STURDY","MIGHTY","POTENT","STALWART","FORMIDABLE","STOUT","BRAWNY","RESILIENT"],
  "Words meaning 'stubborn'": ["OBSTINATE","HEADSTRONG","ADAMANT","TENACIOUS","DOGGED","RESOLUTE","MULISH","UNYIELDING","INTRACTABLE"],
  "Words meaning 'surprise'": ["ASTONISH","STARTLE","STAGGER","FLABBERGAST","DUMBFOUND","STUPEFY","JOLT","BEWILDER","BAMBOOZLE"],
  "Words meaning 'thin'": ["SLENDER","GAUNT","LANKY","WILLOWY","REEDY","WIRY","SVELTE","LEAN","SPINDLY","SCRAWNY","LITHE"],
  "Words meaning 'tip'": ["APEX","SUMMIT","PINNACLE","CREST","ZENITH","PEAK","CROWN","VERTEX","ACME","CAP"],
  "Words meaning 'ugly'": ["HIDEOUS","GROTESQUE","GHASTLY","UNSIGHTLY","GRISLY","HEINOUS","GARISH","GHOULISH","MACABRE"],
  "Words meaning 'walk'": ["STROLL","SAUNTER","AMBLE","TRUDGE","PLOD","STRIDE","LUMBER","MOSEY","MEANDER","WANDER","RAMBLE"],
  "Words meaning 'weird'": ["BIZARRE","PECULIAR","ODD","QUIRKY","EERIE","UNCANNY","SURREAL","OUTLANDISH","OFFBEAT","ZANY"],
  "Words meaning 'wet'": ["DAMP","MOIST","SODDEN","DRENCHED","SOAKED","CLAMMY","SOGGY","SATURATED","DEWY","WATERLOGGED"],
  "Words that mean 'excellent'": ["SUPERB","STELLAR","SPLENDID","MAGNIFICENT","OUTSTANDING","BRILLIANT","FIRST-RATE","SUPERLATIVE"],
  "Words associated with royalty": ["THRONE","SCEPTER","CROWN","PALACE","REGENT","MONARCH","SOVEREIGN","DUKE","EARL","BARON"],
  "Words meaning 'tricky'": ["DEVIOUS","CRAFTY","CUNNING","SLY","ARTFUL","WILY","SHREWD","FOXY","SCHEMING","SUBTLE"],

  // VERB SYNONYMS
  "Words meaning 'to absorb'": ["SOAK","IMBIBE","ENGULF","ASSIMILATE","DEVOUR","CONSUME","SPONGE","DRINK","INGEST"],
  "Words meaning 'to admire'": ["REVERE","ESTEEM","CHERISH","ADORE","VENERATE","IDOLIZE","WORSHIP","PRIZE","TREASURE"],
  "Words meaning 'to agree'": ["CONCUR","ASSENT","COMPLY","CONSENT","ACCEDE","ENDORSE","AFFIRM","RATIFY","SANCTION"],
  "Words meaning 'to anger'": ["RILE","INCENSE","PROVOKE","ENRAGE","INFLAME","INFURIATE","AGGRAVATE","EXASPERATE","NETTLE","MADDEN"],
  "Words meaning 'to annoy'": ["PESTER","IRKED","HARASS","NETTLE","GRATE","BADGER","PLAGUE","HASSLE","NEEDLE","RANKLE"],
  "Words meaning 'to argue'": ["BICKER","QUARREL","SPAR","CLASH","WRANGLE","SQUABBLE","DISPUTE","FEUD","TIFF","CONTEND"],
  "Words meaning 'to avoid'": ["EVADE","ELUDE","DODGE","SHUN","SIDESTEP","CIRCUMVENT","SKIRT","SHIRK","DUCK","ESCHEW"],
  "Words meaning 'to baffle'": ["PERPLEX","BEMUSE","MYSTIFY","CONFOUND","BEWILDER","STUMP","PUZZLE","FLUMMOX","NONPLUS"],
  "Words meaning 'to ban'": ["PROHIBIT","FORBID","OUTLAW","VETO","BAR","EMBARGO","PROSCRIBE","EXCLUDE","INTERDICT"],
  "Words meaning 'to beg'": ["PLEAD","IMPLORE","BESEECH","ENTREAT","SUPPLICATE","GROVEL","PETITION","APPEAL","PRAY"],
  "Words meaning 'to bewitch'": ["ENCHANT","MESMERIZE","CAPTIVATE","ENTRANCE","BEGUILE","CHARM","SPELLBIND","ENTHRALL","BEWITCH"],
  "Words meaning 'to boast'": ["BRAG","GLOAT","CROW","SWAGGER","VAUNT","TRUMPET","SHOWBOAT","BLUSTER","STRUT","PREEN"],
  "Words meaning 'to bother'": ["HASSLE","PESTER","HARASS","BADGER","IRK","NEEDLE","NAG","ANNOY","PLAGUE","DISTURB"],
  "Words meaning 'to break'": ["SHATTER","SMASH","FRACTURE","RUPTURE","SNAP","SPLINTER","CRACK","DEMOLISH","REND","CLEAVE"],
  "Words meaning 'to calm down'": ["SOOTHE","PACIFY","PLACATE","MOLLIFY","APPEASE","QUELL","ASSUAGE","TEMPER","ALLAY"],
  "Words meaning 'to charm'": ["BEGUILE","ENCHANT","CAPTIVATE","ALLURE","BEWITCH","ENTRANCE","MESMERIZE","FASCINATE","DISARM"],
  "Words meaning 'to cheat'": ["SWINDLE","DUPE","DEFRAUD","FLEECE","BILK","HOODWINK","CON","BAMBOOZLE","GRIFT","SCAM"],
  "Words meaning 'to climb'": ["ASCEND","SCALE","SCRAMBLE","CLAMBER","MOUNT","SHINNY","SUMMIT","HIKE","SURMOUNT","CREST"],
  "Words meaning 'to confuse'": ["BAFFLE","PERPLEX","BEWILDER","MYSTIFY","MUDDLE","FLUSTER","BEFUDDLE","DISCOMBOBULATE","ADDLE"],
  "Words meaning 'to copy'": ["MIMIC","EMULATE","REPLICATE","CLONE","FORGE","IMITATE","DUPLICATE","REPRODUCE","PARROT","APE"],
  "Words meaning 'to criticize'": ["LAMBASTE","REBUKE","CENSURE","BERATE","CHIDE","ADMONISH","CASTIGATE","DENOUNCE","UPBRAID"],
  "Words meaning 'to cut'": ["SEVER","CLEAVE","SLICE","CARVE","HACK","SHEAR","TRIM","MINCE","DICE","WHITTLE","PARE"],
  "Words meaning 'to decrease'": ["DIMINISH","DWINDLE","WANE","SHRINK","ABATE","SUBSIDE","TAPER","RECEDE","EBB","DECLINE"],
  "Words meaning 'to defeat'": ["VANQUISH","CONQUER","TROUNCE","ROUT","OVERCOME","SUBDUE","CRUSH","TOPPLE","DEMOLISH","BEST"],
  "Words meaning 'to delay'": ["POSTPONE","DEFER","STALL","PROCRASTINATE","DAWDLE","LINGER","TARRY","DALLY","BIDE","SHELVE"],
  "Words meaning 'to deny'": ["REFUTE","REBUFF","REJECT","REPUDIATE","DISAVOW","DISCLAIM","NEGATE","DISPUTE","CONTEST"],
  "Words meaning 'to destroy'": ["DEMOLISH","ANNIHILATE","OBLITERATE","DECIMATE","RAZE","RAVAGE","WRECK","RUIN","DEVASTATE"],
  "Words meaning 'to eat greedily'": ["DEVOUR","GORGE","GOBBLE","WOLF","GUZZLE","INHALE","SCARF","BOLT","STUFF","SHOVEL"],
  "Words meaning 'to eat'": ["DEVOUR","CONSUME","MUNCH","CHOMP","NIBBLE","GORGE","FEAST","SAVOR","GULP","SNACK"],
  "Words meaning 'to enchant'": ["BEGUILE","CAPTIVATE","MESMERIZE","ENTRANCE","BEWITCH","CHARM","SPELLBIND","FASCINATE"],
  "Words meaning 'to erase'": ["EXPUNGE","OBLITERATE","EFFACE","DELETE","WIPE","PURGE","ANNUL","SCRUB","REMOVE","CANCEL"],
  "Words meaning 'to fix'": ["MEND","REPAIR","PATCH","RESTORE","REMEDY","RECTIFY","AMEND","OVERHAUL","REVAMP","HEAL"],
  "Words meaning 'to flaunt'": ["PARADE","BRANDISH","EXHIBIT","DISPLAY","SHOWCASE","SHOW OFF","STRUT","FLASH","VAUNT"],
  "Words meaning 'to flee'": ["BOLT","SCRAM","SCATTER","ABSCOND","ESCAPE","EVACUATE","RETREAT","DESERT","DECAMP","SKEDADDLE"],
  "Words meaning 'to flourish'": ["THRIVE","PROSPER","BLOOM","BLOSSOM","BURGEON","BOOM","SOAR","SURGE","ABOUND","MUSHROOM"],
  "Words meaning 'to forbid'": ["PROHIBIT","BAN","OUTLAW","VETO","BAR","PROSCRIBE","INTERDICT","EMBARGO","DISALLOW","RESTRICT"],
  "Words meaning 'to gather'": ["COLLECT","AMASS","ACCRUE","ASSEMBLE","MUSTER","CONVENE","RALLY","CONGREGATE","CONVERGE","COMPILE"],
  "Words meaning 'to glow'": ["GLEAM","SHIMMER","RADIATE","BLAZE","FLICKER","SMOLDER","GLIMMER","BEAM","KINDLE","LUMINESCE"],
  "Words meaning 'to grab'": ["SEIZE","SNATCH","CLUTCH","GRASP","NAB","GRIP","CLASP","WREST","POUNCE","LATCH"],
  "Words meaning 'to grip'": ["CLUTCH","CLASP","CLENCH","GRASP","SEIZE","SQUEEZE","HOLD","WRING","EMBRACE","LATCH"],
  "Words meaning 'to help'": ["ASSIST","AID","SUPPORT","BOLSTER","FACILITATE","FOSTER","NURTURE","SUSTAIN","CHAMPION","SERVE"],
  "Words meaning 'to hide'": ["CONCEAL","CLOAK","MASK","VEIL","SHROUD","OBSCURE","CAMOUFLAGE","STASH","SECRETE","LURK"],
  "Words meaning 'to hoard'": ["STOCKPILE","AMASS","CACHE","STASH","SQUIRREL","COLLECT","ACCUMULATE","GARNER","HORDE","STORE"],
  "Words meaning 'to honor'": ["SALUTE","ACCLAIM","REVERE","CELEBRATE","TRIBUTE","COMMEND","LAUD","EXTOL","EXALT","GLORIFY"],
  "Words meaning 'to hurry'": ["RUSH","DASH","HASTEN","SCURRY","HUSTLE","SCRAMBLE","SPRINT","RACE","BOLT","BARREL"],
  "Words meaning 'to ignite'": ["KINDLE","SPARK","LIGHT","TORCH","FUEL","INFLAME","DETONATE","COMBUST","BLAZE","FIRE"],
  "Words meaning 'to jump'": ["LEAP","BOUND","VAULT","SPRING","HOP","BOUNCE","HURDLE","POUNCE","LUNGE","CATAPULT"],
  "Words meaning 'to leave quickly'": ["BOLT","DASH","FLEE","SCRAM","SCARPER","VAMOOSE","SKEDADDLE","HUSTLE","SCRAMBLE","HIGHTAIL"],
  "Words meaning 'to lessen'": ["DIMINISH","DWINDLE","ABATE","WANE","SUBSIDE","TAPER","EASE","MODERATE","EBB","SHRINK"],
  "Words meaning 'to linger'": ["TARRY","DAWDLE","LOITER","DALLY","DWELL","REMAIN","HOVER","PERSIST","STRAGGLE","IDLE"],
  "Words meaning 'to look'": ["GAZE","PEER","GLANCE","SQUINT","STARE","OGLE","PEEP","SURVEY","SCRUTINIZE","BEHOLD"],
  "Words meaning 'to mix'": ["BLEND","MINGLE","MERGE","FUSE","COMBINE","STIR","JUMBLE","MUDDLE","AMALGAMATE","WHISK"],
  "Words meaning 'to mock'": ["RIDICULE","TAUNT","JEER","SCOFF","DERIDE","SNEER","LAMPOON","PARODY","SATIRIZE","RAZZ"],
  "Words meaning 'to outwit'": ["OUTFOX","OUTSMART","OUTMANEUVER","DECEIVE","TRICK","DUPE","BAMBOOZLE","HOODWINK","FOIL","THWART"],
  "Words meaning 'to pamper'": ["CODDLE","SPOIL","INDULGE","COSSET","DOTE","BABY","MOLLYCODDLE","CHERISH","LAVISH","NURTURE"],
  "Words meaning 'to persuade'": ["COAX","ENTICE","COMPEL","CONVINCE","CAJOLE","SWAY","URGE","INFLUENCE","IMPLORE","EXHORT"],
  "Words meaning 'to ponder'": ["MUSE","REFLECT","CONTEMPLATE","RUMINATE","DELIBERATE","MEDITATE","BROOD","MULL","COGITATE","CONSIDER"],
  "Words meaning 'to praise'": ["LAUD","EXTOL","ACCLAIM","APPLAUD","COMMEND","EXALT","GLORIFY","HONOR","CELEBRATE","HAIL"],
  "Words meaning 'to predict'": ["AUGUR","PROPHESY","DIVINE","FORETELL","FORESEE","FORECAST","PORTEND","PRESAGE","PROGNOSTICATE"],
  "Words meaning 'to reveal'": ["EXPOSE","UNVEIL","DISCLOSE","DIVULGE","UNMASK","UNCOVER","BETRAY","MANIFEST","BARE","DISPLAY"],
  "Words meaning 'to rush'": ["DASH","HURTLE","CHARGE","SPRINT","BARREL","BOLT","CAREEN","STAMPEDE","SURGE","SCRAMBLE"],
  "Words meaning 'to scatter'": ["DISPERSE","STREW","SPREAD","SPLAY","DIFFUSE","DISSEMINATE","BROADCAST","FLING","TOSS","SPRAY"],
  "Words meaning 'to scold'": ["REBUKE","CHIDE","BERATE","ADMONISH","REPRIMAND","CENSURE","CASTIGATE","UPBRAID","LAMBASTE"],
  "Words meaning 'to scorch'": ["SINGE","CHAR","SEAR","BLISTER","PARCH","WITHER","BURN","BRAND","TOAST","BLACKEN"],
  "Words meaning 'to shake'": ["QUIVER","TREMBLE","SHUDDER","QUAKE","VIBRATE","RATTLE","JOLT","WOBBLE","SHIVER","CONVULSE"],
  "Words meaning 'to shatter'": ["SMASH","SPLINTER","FRACTURE","DEMOLISH","RUPTURE","BURST","EXPLODE","PULVERIZE","DISINTEGRATE"],
  "Words meaning 'to shine'": ["GLEAM","GLISTEN","SHIMMER","RADIATE","GLITTER","GLOW","SPARKLE","BEAM","TWINKLE","FLASH"],
  "Words meaning 'to shout'": ["BELLOW","ROAR","HOLLER","YELL","SCREECH","CLAMOR","BARK","THUNDER","BOOM","BLARE"],
  "Words meaning 'to shrink'": ["WANE","DWINDLE","RECOIL","SHRIVEL","CONTRACT","DIMINISH","RECEDE","DEFLATE","COMPRESS","WILT"],
  "Words meaning 'to soften'": ["MELLOW","TEMPER","CUSHION","EASE","MODERATE","RELENT","SOOTHE","BLUNT","MUFFLE","DULL"],
  "Words meaning 'to soothe'": ["PACIFY","CALM","COMFORT","EASE","PLACATE","MOLLIFY","CONSOLE","REASSURE","SALVE","BALM"],
  "Words meaning 'to sparkle'": ["GLITTER","SHIMMER","TWINKLE","GLEAM","GLISTEN","FLASH","SCINTILLATE","CORUSCATE","DAZZLE"],
  "Words meaning 'to steal'": ["PILFER","SWIPE","FILCH","PURLOIN","PLUNDER","PINCH","POCKET","SNATCH","EMBEZZLE","LOOT"],
  "Words meaning 'to stop'": ["HALT","CEASE","DESIST","QUIT","SUSPEND","DISCONTINUE","FREEZE","ABORT","TERMINATE","STALL"],
  "Words meaning 'to strengthen'": ["FORTIFY","REINFORCE","BOLSTER","BUTTRESS","BRACE","STEEL","HARDEN","SOLIDIFY","TOUGHEN"],
  "Words meaning 'to stun'": ["DAZE","STAGGER","STUPEFY","SHOCK","PARALYZE","DUMBFOUND","BEWILDER","FLABBERGAST","AWE"],
  "Words meaning 'to suggest'": ["IMPLY","INTIMATE","HINT","INSINUATE","PROPOSE","RECOMMEND","ADVOCATE","COUNSEL","URGE"],
  "Words meaning 'to sway'": ["INFLUENCE","PERSUADE","WAVER","VACILLATE","OSCILLATE","TOTTER","ROCK","LEAN","FLUCTUATE"],
  "Words meaning 'to think'": ["PONDER","REFLECT","MUSE","CONTEMPLATE","RUMINATE","DELIBERATE","MEDITATE","COGITATE","CONSIDER"],
  "Words meaning 'to throw'": ["HURL","TOSS","FLING","CHUCK","LOB","HEAVE","PITCH","SLING","CATAPULT","LAUNCH"],
  "Words meaning 'to thwart'": ["FOIL","STYMIE","IMPEDE","OBSTRUCT","HINDER","HAMPER","FRUSTRATE","BLOCK","DERAIL","SABOTAGE"],
  "Words meaning 'to tremble'": ["QUIVER","SHAKE","SHUDDER","QUAKE","SHIVER","VIBRATE","WOBBLE","FLUTTER","PALPITATE","JUDDER"],
  "Words meaning 'to trick'": ["DUPE","DECEIVE","SWINDLE","CON","BAMBOOZLE","HOODWINK","BEGUILE","MISLEAD","DELUDE","BLUFF"],
  "Words meaning 'to try'": ["ATTEMPT","ENDEAVOR","STRIVE","STRUGGLE","VENTURE","ASPIRE","TACKLE","UNDERTAKE","PURSUE"],
  "Words meaning 'to vanish'": ["DISAPPEAR","EVAPORATE","DISSOLVE","FADE","PERISH","RECEDE","DISPERSE","DISSIPATE","MELT","WANE"],
  "Words meaning 'to wander aimlessly'": ["MEANDER","DRIFT","ROAM","RAMBLE","STRAY","ROVE","TRAIPSE","GALLIVANT","MOSEY","WANDER"],
  "Words meaning 'to wander'": ["ROAM","DRIFT","MEANDER","RAMBLE","STRAY","ROVE","TRAIPSE","MOSEY","AMBLE","GALLIVANT"],
  "Words meaning 'to weaken'": ["UNDERMINE","ERODE","SAP","ENFEEBLE","DILUTE","SMOTHER","CRIPPLE","DEBILITATE","IMPAIR","DRAIN"],

  // MATH, SCIENCE, MISC
  "Math concepts": ["PRIME","MATRIX","FUNCTION","THEOREM","INTEGRAL","VECTOR","FRACTAL","ALGORITHM","DERIVATIVE","ASYMPTOTE"],
  "Camping gear": ["TENT","FLASHLIGHT","COMPASS","CANTEEN","TARP","SLEEPING BAG","HATCHET","BINOCULARS","STOVE","LANTERN"],
  "Famous Georges": ["WASHINGTON","CLOONEY","HARRISON","FOREMAN","LUCAS","ORWELL","STRAIT","BURNS","CARLIN","MICHAEL"],
};

// ── 2. FIX MISCATEGORIZED WORDS ─────────────────────────────────────────
const WORD_FIXES = [
  { puzzleId: 9, category: "Things with wings", oldWord: "STAGE", newWord: "DRAGONFLY" },
  { puzzleId: 222, category: "Things with wings", oldWord: "STAGE", newWord: "MOTH" },
  { puzzleId: 98, category: "Deer species", oldWord: "ANTELOPE", newWord: "MUNTJAC" },
  { puzzleId: 160, category: "Salamanders", oldWord: "AXE", newWord: "AXOLOTL" },
  { puzzleId: 226, category: "Words meaning 'to glow'", oldWord: "LUMINOUS", newWord: "GLEAM" },
  { puzzleId: 267, category: "Words meaning 'to glow'", oldWord: "LUMINOUS", newWord: "SMOLDER" },
  { puzzleId: 258, category: "Sharks", oldWord: "HAMMER", newWord: "HAMMERHEAD" },
  { puzzleId: 272, category: "Words meaning 'to flaunt'", oldWord: "FLAUNT", newWord: "PARADE" },
  { puzzleId: 283, category: "Cactus types", oldWord: "PRICKLY", newWord: "PRICKLY PEAR" },
];

// ── 3. WORD FRAGMENT FIXES ──────────────────────────────────────────────
const FRAGMENT_FIXES = {
  "NING": "BEACON",
  "RUPT": "FRACTURE",
  "FLIX": "CINEMA",
  "ISHED": "COBALT",
};

// ── APPLY FIXES ─────────────────────────────────────────────────────────
let totalFixes = 0;

// Fix miscategorized words
WORD_FIXES.forEach(fix => {
  const puzzle = PUZZLES.find(p => p.id === fix.puzzleId);
  if (!puzzle) { console.log(`Puzzle ${fix.puzzleId} not found!`); return; }
  const group = puzzle.groups.find(g => g.category === fix.category);
  if (!group) { console.log(`Category "${fix.category}" not found in puzzle ${fix.puzzleId}!`); return; }
  const idx = group.words.indexOf(fix.oldWord);
  if (idx === -1) { console.log(`Word "${fix.oldWord}" not found in ${fix.category} of puzzle ${fix.puzzleId}!`); return; }

  // Make sure newWord isn't already in the puzzle
  const allWords = new Set([...puzzle.groups.flatMap(g => g.words), ...puzzle.decoys]);
  if (allWords.has(fix.newWord)) {
    console.log(`WARNING: "${fix.newWord}" already exists in puzzle ${fix.puzzleId}, skipping`);
    return;
  }

  group.words[idx] = fix.newWord;
  console.log(`P${fix.puzzleId}: Fixed "${fix.oldWord}" -> "${fix.newWord}" in [${fix.category}]`);
  totalFixes++;
});

// Fix word fragments (in decoys)
PUZZLES.forEach(p => {
  p.decoys = p.decoys.map(d => {
    if (FRAGMENT_FIXES[d]) {
      const allWords = new Set([...p.groups.flatMap(g => g.words), ...p.decoys]);
      let replacement = FRAGMENT_FIXES[d];
      if (allWords.has(replacement)) {
        replacement = replacement + '_ALT';
      }
      console.log(`P${p.id}: Fixed fragment "${d}" -> "${replacement}" in decoys`);
      totalFixes++;
      return replacement;
    }
    return d;
  });
});

// Fix word fragments (in groups — check just in case)
PUZZLES.forEach(p => {
  p.groups.forEach(g => {
    g.words = g.words.map(w => {
      if (FRAGMENT_FIXES[w]) {
        console.log(`P${p.id}: Fixed fragment "${w}" -> "${FRAGMENT_FIXES[w]}" in [${g.category}]`);
        totalFixes++;
        return FRAGMENT_FIXES[w];
      }
      return w;
    });
  });
});

console.log(`\n--- Structural fixes: ${totalFixes} ---\n`);

// ── 4. FIX ALL BAD DECOYS ───────────────────────────────────────────────
// For each puzzle, evaluate each decoy: does it plausibly fit any of the puzzle's categories?
// If not, replace it with a word from one of the category pools.

function isPlausibleDecoy(word, categories, groupWords) {
  // A decoy is plausible if it could belong to any of the puzzle's categories
  for (const cat of categories) {
    const pool = CAT_POOL[cat];
    if (!pool) continue;
    // Check if the word is in the pool (meaning it's a valid member of that category)
    if (pool.includes(word)) return true;
  }

  // Also check: is the word actually in a group's words list for a matching category?
  // (This covers cases where a word IS a valid member but isn't in our pool)
  // We'll be conservative: if we don't have a pool, we can't judge
  const hasPools = categories.some(c => CAT_POOL[c]);
  if (!hasPools) return true; // Can't evaluate - keep it

  return false;
}

let decoyFixes = 0;
const globalUsed = new Set();
// Collect all words used across ALL puzzles to avoid cross-puzzle issues
PUZZLES.forEach(p => {
  p.groups.forEach(g => g.words.forEach(w => globalUsed.add(w)));
  p.decoys.forEach(d => globalUsed.add(d));
});

PUZZLES.forEach(p => {
  const categories = p.groups.map(g => g.category);
  const puzzleWords = new Set([...p.groups.flatMap(g => g.words), ...p.decoys]);
  const hasPools = categories.some(c => CAT_POOL[c]);

  if (!hasPools) return; // No pools for any category, skip

  const newDecoys = [];
  p.decoys.forEach(d => {
    if (isPlausibleDecoy(d, categories, puzzleWords)) {
      newDecoys.push(d);
      return;
    }

    // Find a replacement from one of the category pools
    let replacement = null;
    // Shuffle categories to distribute across groups
    const shuffledCats = [...categories].sort(() => Math.random() - 0.5);

    for (const cat of shuffledCats) {
      const pool = CAT_POOL[cat];
      if (!pool) continue;
      for (const candidate of pool) {
        if (!puzzleWords.has(candidate) && !newDecoys.includes(candidate)) {
          replacement = candidate;
          break;
        }
      }
      if (replacement) break;
    }

    if (replacement) {
      newDecoys.push(replacement);
      puzzleWords.add(replacement);
      decoyFixes++;
      console.log(`P${p.id}: Replaced decoy "${d}" -> "${replacement}" (for [${categories.join(', ')}])`);
    } else {
      newDecoys.push(d);
      console.log(`P${p.id}: Could not find replacement for decoy "${d}"`);
    }
  });

  p.decoys = newDecoys;
});

console.log(`\n--- Decoy fixes: ${decoyFixes} ---`);
console.log(`--- Total fixes: ${totalFixes + decoyFixes} ---\n`);

// ── VERIFY ──────────────────────────────────────────────────────────────
let ok = true;
PUZZLES.forEach(p => {
  const all = [...p.groups.flatMap(g => g.words), ...p.decoys];
  if (new Set(all).size !== all.length) {
    const counts = {};
    all.forEach(w => { counts[w] = (counts[w] || 0) + 1; });
    const dupes = Object.entries(counts).filter(([, c]) => c > 1).map(([w]) => w);
    console.log(`DUPLICATE in puzzle ${p.id}: ${dupes.join(', ')}`);
    ok = false;
  }
});
if (ok) console.log('All puzzles clean — no duplicates.');

// Check that all decoys are now plausible
let stillBad = 0;
PUZZLES.forEach(p => {
  const categories = p.groups.map(g => g.category);
  const hasPools = categories.some(c => CAT_POOL[c]);
  if (!hasPools) return;

  p.decoys.forEach(d => {
    if (!isPlausibleDecoy(d, categories, new Set())) {
      stillBad++;
    }
  });
});
console.log(`Remaining bad decoys: ${stillBad}`);

// ── WRITE OUTPUT ────────────────────────────────────────────────────────
let output = 'const PUZZLES = [\n';
PUZZLES.forEach((puzzle, pi) => {
  output += '  {\n';
  output += `    id: ${puzzle.id},\n`;
  output += '    groups: [\n';
  puzzle.groups.forEach((g, gi) => {
    const words = g.words.map(w => JSON.stringify(w)).join(', ');
    output += `      { category: ${JSON.stringify(g.category)}, words: [${words}] }`;
    output += gi < puzzle.groups.length - 1 ? ',\n' : '\n';
  });
  output += '    ],\n';
  const decoyStr = puzzle.decoys.map(d => JSON.stringify(d)).join(', ');
  output += `    decoys: [${decoyStr}]\n`;
  output += '  }';
  output += pi < PUZZLES.length - 1 ? ',\n' : '\n';
});
output += '];\n';
fs.writeFileSync(__dirname + '/puzzles.js', output);
console.log('Written', PUZZLES.length, 'puzzles to puzzles.js');
